version: '2'
linters:
  default: all
  disable:
    - depguard # too complex to maintain
    - nlreturn # don't want
    - noinlineerr # don't agree with
    - paralleltest # breaks some tests
    - varnamelen # don't agree with
    - wsl # don't want
    - wsl_v5 # don't want
  settings:
    sloglint:
      attr-only: true
    cyclop:
      max-complexity: 20
    funlen:
      lines: 70
      statements: 50
      ignore-comments: true
    gosec:
      excludes:
        - G203
    misspell:
      locale: US
      ignore-rules:
        - Teh
    mnd:
      ignored-files:
        - interview.go
        - janeway.go
        - milestone.go
        - zoo.go
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .HTML(
        - .Inline(
        - .JSON(
        - .JSONPretty(
        - .Redirect(
        - .Render(
        - .String(
        - .Text(
        - app.StatusErr(
      ignore-package-globs:
        - github.com/aarondl/sqlboiler/v4/*
        - github.com/aarondl/sqlboiler/*
        - github.com/Defacto2/server/internal/postgres/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: ^model/files\.go$
      # UNIT & GO TESTS
      - linters:
          - cyclop
          - dogsled
          - dupl
          - exhaustive
          - exhaustruct
          - funlen
          - gocyclo
          - ireturn
          - lll
          - misspell
          - mnd
          - wrapcheck
        path: _test\.go$
      # BELOW EXCLUSIONS ARE ALL REQUIRED
      - linters:
          - lll
        path: doc.go
      - linters:
          - exhaustruct
          - lll
        path: handler/app/milestone.go
      - linters:
          - lll
        path: handler/jsdos/jsdos.go
      - linters:
          - lll
          - tagalign
        path: internal/config/config.go
      - linters:
          - ireturn
        path: model/querymod/querymod.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
