version: '2'
linters:
  default: all
  disable:
    # conflicts
    - contextcheck # conflicts with echo patterns
    #- depguard # too complex to maintain with this app
    - gomoddirectives # required at the moment (for: task doc)
    # retired
    - exhaustruct
    - gomodguard
    - wsl
    # the linters below are unwanted
    - nlreturn
    - noinlineerr
    - varnamelen
    - wsl_v5
    - godox # FIX: remove
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - 'github.com/Defacto2/server'
            - 'github.com/Defacto2/archive'
            - 'github.com/Defacto2/helper'
            - 'github.com/Defacto2/magicnumber'
            - 'github.com/bengarrett/ansibump'
            - 'github.com/bengarrett/binbump'
            - 'github.com/bengarrett/bbs'
            - 'github.com/bengarrett/sauce'
            - 'github.com/aarondl/null/v8'
            - 'github.com/aarondl/sqlboiler/v4'
            - 'github.com/aarondl/strmangle'
            - 'github.com/caarlos0/env/v11'
            - 'github.com/carlmjohnson/versioninfo'
            - 'github.com/dustin/go-humanize'
            - 'github.com/labstack/echo/v5'
            - 'github.com/labstack/echo-contrib/v5'
            - 'github.com/lmittmann/tint'
            - 'github.com/jackc/pgx/v5'
            - 'github.com/h2non/filetype'
            - 'github.com/gomarkdown/markdown'
            - 'github.com/gorilla/sessions'
            - 'github.com/mattn/go-isatty'
            - 'github.com/microcosm-cc/bluemonday'
            - 'github.com/nalgeon/be'
            - 'github.com/rosedblabs/rosedb/v2'
            - 'github.com/samber/slog-multi'
            - 'github.com/subpop/go-ini'
            - 'github.com/google/uuid'
            - 'github.com/urfave/cli/v2'
            - 'github.com/wizenheimer/blaze'
            - 'github.com/writeas/go-strip-markdown'
            - 'golang.org/x/image'
            - 'golang.org/x/sync'
            - 'golang.org/x/text'
            - 'google.golang.org/api'
    cyclop:
      max-complexity: 20
    funlen:
      lines: 70
      statements: 50
      ignore-comments: true
    gosec:
      excludes:
        - G203
    misspell:
      locale: US
      ignore-rules:
        - Teh
    sloglint:
      attr-only: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .HTML(
        - .Inline(
        - .JSON(
        - .JSONPretty(
        - .Redirect(
        - .Render(
        - .String(
        - .Text(
        - app.StatusErr(
      ignore-package-globs:
        - github.com/aarondl/sqlboiler/v4/*
        - github.com/aarondl/sqlboiler/*
        - github.com/Defacto2/server/internal/postgres/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: ^model/files\.go$
      # UNIT & GO TESTS
      - linters:
          - cyclop
          - dogsled
          - dupl
          - exhaustive
          - exhaustruct_v5
          - funlen
          - goconst
          - gochecknoglobals
          - gochecknoinits
          - gocyclo
          - ireturn
          - lll
          - misspell
          - mnd
          - tagliatelle
          - wrapcheck
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
