package app_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"

	"github.com/nalgeon/be"
)

/*
* These api_test.go and api_*_test.go files were all generated by Minstal's devstral-2 model,
* with some minor manual tweaks by myself.
 */

const (
	lh  = "http://localhost:1323"
	api = lh + "/api/v0"
)

// TestMain checks server availability before running tests.
func TestMain(m *testing.M) {
	// Check if server is running.
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, lh+"/health-check", nil)
	resp, err := client.Do(req)
	if err != nil {
		_, _ = os.Stderr.WriteString("SKIP: Server not running at localhost:1323\n")
		os.Exit(0)
	}
	_ = resp.Body.Close()

	// Run tests if server is available.
	code := m.Run()
	os.Exit(code)
}

// TestAnnouncementsContract verifies the announcements endpoint contract.
func TestAnnouncementsContract(t *testing.T) {
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/category/announcements", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()

	be.Equal(t, http.StatusOK, resp.StatusCode)

	var result struct {
		Files []struct {
			ID          int64  `json:"id"`
			Filename    string `json:"filename"`
			Description string `json:"description"`
			FileType    string `json:"fileType"`
			URLs        struct {
				Download  string `json:"download"`
				HTML      string `json:"html"`
				Thumbnail string `json:"thumbnail,omitempty"`
			} `json:"urls"`
		} `json:"files"`
	}

	body, err := io.ReadAll(resp.Body)
	be.Equal(t, err, nil)

	err = json.Unmarshal(body, &result)
	be.Equal(t, err, nil)

	be.True(t, len(result.Files) > 0)

	// Verify URL patterns
	for _, file := range result.Files {
		be.True(t, strings.HasPrefix(file.URLs.Download, "/d/"))
		be.True(t, strings.HasPrefix(file.URLs.HTML, "/f/"))
		be.True(t, len(file.Description) > 0)
	}
}

// TestCategoriesContract verifies the categories endpoint contract.
func TestCategoriesContract(t *testing.T) {
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/categories", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()
	be.Equal(t, http.StatusOK, resp.StatusCode)

	var result []struct {
		ID          int    `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description,omitempty"`
		URI         string `json:"uri"`
		URLs        struct {
			API   string `json:"api"`
			HTML3 string `json:"html3"`
			HTML  string `json:"html"`
		} `json:"urls"`
	}

	body, err := io.ReadAll(resp.Body)
	be.Equal(t, err, nil)

	err = json.Unmarshal(body, &result)
	be.Equal(t, err, nil)

	be.True(t, len(result) > 0)

	// Verify at least one category has proper structure
	be.True(t, len(result[0].Name) > 0)
	be.True(t, strings.HasPrefix(result[0].URLs.API, "/api/v0/files/"))
	be.True(t, strings.HasPrefix(result[0].URLs.HTML3, "/html3/"))
	be.True(t, strings.HasPrefix(result[0].URLs.HTML, "/files/"))
}

// TestPlatformsContract verifies the platforms endpoint contract.
func TestPlatformsContract(t *testing.T) {
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/platforms", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()

	be.Equal(t, http.StatusOK, resp.StatusCode)

	var result []struct {
		ID          int    `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description,omitempty"`
		URI         string `json:"uri"`
		URLs        struct {
			API   string `json:"api"`
			HTML3 string `json:"html3"`
			HTML  string `json:"html"`
		} `json:"urls"`
	}

	body, err := io.ReadAll(resp.Body)
	be.Equal(t, err, nil)

	err = json.Unmarshal(body, &result)
	be.Equal(t, err, nil)

	be.True(t, len(result) > 0)

	// Verify at least one platform has proper structure
	be.True(t, len(result[0].Name) > 0)
	be.True(t, strings.HasPrefix(result[0].URLs.API, "/api/v0/files/"))
	be.True(t, strings.HasPrefix(result[0].URLs.HTML3, "/html3/"))
	be.True(t, strings.HasPrefix(result[0].URLs.HTML, "/files/"))
}

// TestGenericCategoryContract verifies the generic category endpoint contract.
func TestGenericCategoryContract(t *testing.T) {
	testCases := []string{"demo", "scenerules", "magazine"}

	for _, category := range testCases {
		t.Run(category, func(t *testing.T) {
			url := api + "/category/" + category
			client := http.Client{}
			req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
			resp, err := client.Do(req)
			be.Equal(t, err, nil)
			defer func() {
				if err := resp.Body.Close(); err != nil {
					t.Log(err)
				}
			}()
			be.Equal(t, http.StatusOK, resp.StatusCode)

			var result struct {
				Files []struct {
					ID          int64  `json:"id"`
					Filename    string `json:"filename"`
					Description string `json:"description"`
					URLs        struct {
						Download  string `json:"download"`
						HTML      string `json:"html"`
						Thumbnail string `json:"thumbnail,omitempty"`
					} `json:"urls"`
				} `json:"files"`
			}

			body, err := io.ReadAll(resp.Body)
			be.Equal(t, err, nil)

			err = json.Unmarshal(body, &result)
			be.Equal(t, err, nil)

			// Verify structure (may be empty but should be valid JSON)
			for _, file := range result.Files {
				be.True(t, strings.HasPrefix(file.URLs.Download, "/d/"))
				be.True(t, strings.HasPrefix(file.URLs.HTML, "/f/"))
			}
		})
	}
}

// TestPlatformQueries verifies that platform queries work correctly.
func TestPlatformQueries(t *testing.T) {
	// Test a few different platform types
	platforms := []string{"ansi", "audio", "dos", "windows", "image"}

	for _, platform := range platforms {
		t.Run(platform, func(t *testing.T) {
			url := api + "/platform/" + platform
			client := http.Client{}
			req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
			resp, err := client.Do(req)
			be.Equal(t, err, nil)
			defer func() {
				if err := resp.Body.Close(); err != nil {
					t.Log(err)
				}
			}()

			be.Equal(t, http.StatusOK, resp.StatusCode)

			var result struct {
				Files []struct {
					ID          int64  `json:"id"`
					Filename    string `json:"filename"`
					Description string `json:"description"`
					URLs        struct {
						Download  string `json:"download"`
						HTML      string `json:"html"`
						Thumbnail string `json:"thumbnail,omitempty"`
					} `json:"urls"`
				} `json:"files"`
			}

			body, err := io.ReadAll(resp.Body)
			be.Equal(t, err, nil)

			err = json.Unmarshal(body, &result)
			be.Equal(t, err, nil)

			// Verify URL patterns for platform files
			for _, file := range result.Files {
				be.True(t, strings.HasPrefix(file.URLs.Download, "/d/"))
				be.True(t, strings.HasPrefix(file.URLs.HTML, "/f/"))
			}
		})
	}
}

// TestURLPatterns verifies consistent URL patterns across all endpoints.
func TestURLPatterns(t *testing.T) {
	endpoints := []string{
		"announcements",
		"demo",
		"scenerules",
		"magazine",
	}

	for _, endpoint := range endpoints {
		t.Run(endpoint, func(t *testing.T) {
			url := api + "/category/" + endpoint
			client := http.Client{}
			req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
			resp, err := client.Do(req)
			be.Equal(t, err, nil)
			defer func() {
				if err := resp.Body.Close(); err != nil {
					t.Log(err)
				}
			}()
			be.Equal(t, http.StatusOK, resp.StatusCode)
			// Just verify it returns valid JSON with expected structure
			var result map[string]any
			err = json.NewDecoder(resp.Body).Decode(&result)
			be.Equal(t, err, nil)
			be.True(t, len(result) > 0)
		})
	}
}

// TestScenersContract verifies the sceners endpoint contract.
func TestScenersContract(t *testing.T) {
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/sceners", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()

	be.Equal(t, http.StatusOK, resp.StatusCode)

	var result struct {
		Sceners []struct {
			ID    string `json:"id"`
			Name  string `json:"name"`
			Title string `json:"title"`
			URLs  struct {
				API  string `json:"api"`
				HTML string `json:"html"`
			} `json:"urls"`
		} `json:"sceners"`
		Page       int `json:"page"`
		Totals     int `json:"totals"`
		TotalPages int `json:"totalPages"`
	}

	body, err := io.ReadAll(resp.Body)
	be.Equal(t, err, nil)

	err = json.Unmarshal(body, &result)
	be.Equal(t, err, nil)

	be.True(t, len(result.Sceners) > 0)
	be.Equal(t, 1, result.Page)
	be.True(t, result.Totals > 0)
	be.True(t, result.TotalPages >= 1)

	// Verify URL patterns for sceners
	for _, scener := range result.Sceners {
		be.True(t, len(scener.ID) > 0)
		be.True(t, len(scener.Name) > 0)
		be.True(t, len(scener.Title) > 0)
		be.True(t, strings.HasPrefix(scener.URLs.API, "/api/v0/scener/"))
		be.True(t, strings.HasPrefix(scener.URLs.HTML, "/p/"))
	}
}

// TestScenerRolesContract verifies the scener role endpoints contract.
func TestScenerRolesContract(t *testing.T) {
	roles := []string{"artist", "coder", "musician", "writer"}

	for _, role := range roles {
		t.Run(role, func(t *testing.T) {
			url := api + "/sceners/" + role
			client := http.Client{}
			req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
			resp, err := client.Do(req)
			be.Equal(t, err, nil)
			defer func() {
				if err := resp.Body.Close(); err != nil {
					t.Log(err)
				}
			}()

			be.Equal(t, http.StatusOK, resp.StatusCode)

			var result struct {
				Sceners []struct {
					ID    string `json:"id"`
					Name  string `json:"name"`
					Title string `json:"title"`
					URLs  struct {
						API  string `json:"api"`
						HTML string `json:"html"`
					} `json:"urls"`
				} `json:"sceners"`
				Page       int `json:"page"`
				Totals     int `json:"totals"`
				TotalPages int `json:"totalPages"`
			}

			body, err := io.ReadAll(resp.Body)
			be.Equal(t, err, nil)

			err = json.Unmarshal(body, &result)
			be.Equal(t, err, nil)

			be.True(t, len(result.Sceners) > 0)
			be.Equal(t, 1, result.Page)
			be.True(t, result.Totals > 0)
			be.True(t, result.TotalPages >= 1)

			// Verify URL patterns for role-specific sceners
			for _, scener := range result.Sceners {
				be.True(t, len(scener.ID) > 0)
				be.True(t, len(scener.Name) > 0)
				be.True(t, len(scener.Title) > 0)
				be.True(t, strings.HasPrefix(scener.URLs.API, "/api/v0/scener/"))
				be.True(t, strings.HasPrefix(scener.URLs.HTML, "/p/"))
			}
		})
	}
}

// TestScenerDetailsContract verifies the individual scener details endpoint contract.
func TestScenerDetailsContract(t *testing.T) {
	// Test with a known scener (006 from our earlier tests)
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/scener/006", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()

	be.Equal(t, http.StatusOK, resp.StatusCode)

	var result map[string]any

	body, err := io.ReadAll(resp.Body)
	be.Equal(t, err, nil)

	err = json.Unmarshal(body, &result)
	be.Equal(t, err, nil)

	// Verify basic structure
	be.True(t, len(result) > 0)
	be.True(t, result["scener"] != nil)
	be.True(t, result["files"] != nil)

	scener, ok := result["scener"].(map[string]any)
	be.True(t, ok)
	be.Equal(t, "006", scener["name"])

	id, ok := scener["id"].(string)
	be.True(t, ok && len(id) > 0)

	title, ok := scener["title"].(string)
	be.True(t, ok && len(title) > 0)

	scenerURLs, ok := scener["urls"].(map[string]any)
	be.True(t, ok)

	apiURL, ok := scenerURLs["api"].(string)
	be.True(t, ok && strings.HasPrefix(apiURL, "/api/v0/scener/"))

	htmlURL, ok := scenerURLs["html"].(string)
	be.True(t, ok && strings.HasPrefix(htmlURL, "/p/"))

	stats, ok := scener["statistics"].(map[string]any)
	be.True(t, ok)

	totalFiles, ok := stats["totalFiles"].(float64)
	be.True(t, ok && int(totalFiles) >= 0)

	totalSizeBytes, ok := stats["totalSizeBytes"].(float64)
	be.True(t, ok && int(totalSizeBytes) >= 0)

	// Verify files structure (if any files exist)
	files, ok := result["files"].([]any)
	be.True(t, ok)
	if len(files) > 0 {
		be.True(t, len(files) > 0)

		firstFile, ok := files[0].(map[string]any)
		be.True(t, ok)

		fileID, ok := firstFile["id"].(float64)
		be.True(t, ok && int(fileID) > 0)

		filename, ok := firstFile["filename"].(string)
		be.True(t, ok && len(filename) > 0)

		description, ok := firstFile["description"].(string)
		be.True(t, ok && len(description) > 0)

		fileURLs, ok := firstFile["urls"].(map[string]any)
		be.True(t, ok)

		downloadURL, ok := fileURLs["download"].(string)
		be.True(t, ok && strings.HasPrefix(downloadURL, "/d/"))

		htmlFileURL, ok := fileURLs["html"].(string)
		be.True(t, ok && strings.HasPrefix(htmlFileURL, "/f/"))
	}
}

// TestScenerNotFound verifies the 404 response for non-existent sceners.
func TestScenerNotFound(t *testing.T) {
	client := http.Client{}
	req, _ := http.NewRequestWithContext(context.Background(), http.MethodGet, api+"/scener/nonexistent-scener-12345", nil)
	resp, err := client.Do(req)
	be.Equal(t, err, nil)
	defer func() {
		if err := resp.Body.Close(); err != nil {
			t.Log(err)
		}
	}()

	be.Equal(t, http.StatusNotFound, resp.StatusCode)

	var result map[string]string
	err = json.NewDecoder(resp.Body).Decode(&result)
	be.Equal(t, err, nil)

	be.Equal(t, "Scener not found", result["error"])
}
