linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Run only fast linters from enabled linters set (first run won't be fast).
  # Default: false
  fast: true
  # Disable specific linters.
  disable:
    # 
    - nosnakecase
    - ifshort
    - scopelint
    # disabled for other reasons
    - wsl
    - gochecknoglobals
    - lll
    - gci
    - nlreturn
    - funlen