linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Run only fast linters from enabled linters set (first run won't be fast).
  # Default: false
  fast: true
  # Disable specific linters.
  disable:
    # deprecated
    - nosnakecase
    - ifshort
    - scopelint
    # disabled
    - funlen            # should enable at a later stage. 
    - wsl               # fussy over whitespace.
    - nlreturn          # fussy over whitespace.
    # broken on windows
    - gci
    - gofmt
    - goimports
    # temporary disabled
    - depguard

linters-settings:
  gomnd:
    # List of file patterns to exclude from analysis.
    # Values always ignored: `.+_test.go`
    # Default: []
    ignored-files:
      - 'milestones.go'