linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Run only fast linters from enabled linters set (first run won't be fast).
  # Default: false
  fast: true
  # Disable specific linters.
  disable:
    # deprecated
    - nosnakecase
    - ifshort
    - scopelint
    # disabled
    - funlen            # should enable at a later stage. 
    - wsl               # fussy over whitespace.
    - nlreturn          # fussy over whitespace.
    # broken on windows
    - gci
    - gofmt
    - goimports
    # temporary disabled
    - depguard
    - lll
    - godox

linters-settings:
  gomnd:
    # List of file patterns to exclude from analysis.
    # Values always ignored: `.+_test.go`
    # Default: []
    ignored-files:
      - 'milestones.go' # magic number false positives.
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    # Default is to use a neutral variety of English.
    locale: US
    # Default: []
    ignore-words:
      - 'Teh' # Teh Scene.