# The .golangci.yaml file is used to configure the golangci-lint linter.
# A linter is a tool that analyzes source code to flag programming errors,
# bugs, stylistic errors, and suspicious constructs.
#
# https://golangci-lint.run/
#
linters:
  enable-all: true
  fast: false
  # Disable specific linters.
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled
    - depguard # overkill.
    - exhaustive
    - exhaustruct
    - ireturn # conflicts with sqlboiler.
    - nlreturn # fussy over whitespace.
    - paralleltest # overkill.
    - varnamelen # not idomatic?
    - wrapcheck
    - wsl # fussy over whitespace.
    # temporary disabled
    #- godox
issues:
  exclude-rules:
    - path: cmd/cmd.go
      linters:
        - gosmopolitan
    - path: doc.go
      linters:
        - lll
    - path: handler/app/accordion.go
      linters:
        - lll
        - funlen
    - path: handler/app/context.go
      linters:
        - dupl
        - lll
    - path: handler/app/funchtml.go
      linters:
        - gosec
    - path: handler/app/funcmap.go
      linters:
        - gosec
        - funlen
    - path: handler/app/interview.go
      linters:
        - funlen
    - path: handler/app/milestone.go
      linters:
        - funlen
        - lll
        - maintidx
    - path: handler/app/render_model.go
      linters:
        - cyclop
        - funlen
        - gocyclo
        - maintidx
    - path: handler/app/render_releaser.go
      linters:
        - lll
    - path: handler/app/website.go
      linters:
        - lll
    - path: handler/html3/list.go
      linters:
        - cyclop
        - lll
    - path: handler/router.go
      linters:
        - funlen
        - maintidx
    - path: internal/command/images.go
      linters:
        - lll
    - path: internal/config/config.go
      linters:
        - gocognit
        - lll
        - tagalign
    - path: internal/demozoo/demozoo.go
      linters:
        - tagliatelle
    - path: internal/pouet/pouet.go
      linters:
        - tagliatelle
    - path: internal/postgres/postgres.go
      linters:
        - lll
        - tagalign
    - path: internal/tags/tags.go
      linters:
        - gocyclo
        - gochecknoglobals
    - path: internal/web/web.go
      linters:
        - funlen
        - maintidx
    - path: internal/zoo/zoo.go
      linters:
        - tagliatelle
    - path: model/repair.go
      linters:
        - funlen
    - path: model/summary.go
      linters:
        - gocognit
        - gocyclo
        - maintidx
    - path: runner/runner.go
      linters:
        - funlen
    - path: _test.go
      linters:
        - cyclop
        - funlen
    - path: handler/app/app.go
      linters:
        - gosec
    - path: handler/app/funchtml.go
      linters:
        - gosec
    - path: handler/app/funcmap.go
      linters:
        - gosec
        - funlen
    - path: handler/html3/html3.go
      linters:
        - lll
    - path: handler/app/interview.go
      linters:
        - funlen
    - path: handler/router.go
      linters:
        - funlen
        - maintidx
    - path: handler/app/milestone.go
      linters:
        - funlen
        - maintidx
        - lll
    - path: handler/app/render_model.go
      linters:
        - cyclop
        - gocyclo
        - maintidx
        - funlen
    - path: handler/app/render_releaser.go
      linters:
        - lll
    - path: handler/app/uri.go
      linters:
        - funlen
    - path: handler/app/web.go
      linters:
        - funlen
        - gosec
    - path: handler/app/website.go
      linters:
        - lll
    - path: internal/command/images.go
      linters:
        - lll
    - path: internal/config/config.go
      linters:
        - gocognit
        - lll
        - tagalign
    - path: internal/pouet/pouet.go
      linters:
        - tagliatelle
    - path: internal/zoo/zoo.go
      linters:
        - tagliatelle
    - path: internal/tags/tags.go
      linters:
        - gocyclo
        - gochecknoglobals
    - path: internal/web/web.go
      linters:
        - funlen
    - path: model/filesAnsiArt.go
      linters:
        - dupl
    - path: model/filesBBSAdvert.go
      linters:
        - dupl
    - path: model/filesFilepack.go
      linters:
        - dupl
    - path: model/filesPlatform.go
      linters:
        - dupl
    - path: model/filesText.go
      linters:
        - dupl
    - path: model/repair.go
      linters:
        - funlen
    - path: model/summary.go
      linters:
        - gocognit
        - gocyclo
        - maintidx
    - path: model/fix/fix.go
      linters:
        - lll
    - path: runner/runner.go
      linters:
        - funlen
    - path: archive_test.go
      linters:
        - dupl
    - path: zoo_test.go
      linters:
        - tagliatelle
    - path: jsdos.go
      linters:
        - lll
    - path: internal/postgres/sql.go
      linters:
        - goconst

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 17
    skip-tests: true
  funlen:
    # Maximum function length in lines.
    # Default: 50
    lines: 60
    statements: 45
    ignore-comments: true
  gomnd:
    # List of file patterns to exclude from analysis.
    # Values always ignored: `.+_test.go`
    # Default: []
    ignored-files: # magic number false positives.
      - "milestone.go"
      - "interview.go"
      - "zoo.go"
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    # Default is to use a neutral variety of English.
    locale: US
    # Default: []
    ignore-words:
      - "Teh" # Teh Scene.
