linters:
  enable-all: true
  fast: false
  # Disable specific linters.
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled
    - depguard          # don't need this.
    - exhaustive
    - exhaustruct
    - ireturn
    - nlreturn          # fussy over whitespace.
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl               # fussy over whitespace.
    # temporary disabled
    - godox
    - cyclop
    - funlen            # should enable at a later stage. 
    - stylecheck
issues:
  exclude-rules:
    - path: cmd/cmd.go
      linters:
        - gosmopolitan
    - path: handler/app/funchtml.go
      linters:
        - gosec    
    - path: handler/app/funcmap.go
      linters:
        - gosec
    - path: handler/router.go
      linters:
        - maintidx
    - path: handler/app/milestone.go
      linters:
        - maintidx
        - lll
    - path: handler/app/render_model.go
      linters:
        - gocyclo
        - maintidx
    - path: handler/app/render_releaser.go
      linters:
        - lll
    - path: handler/app/website.go
      linters:
        - lll
    - path: internal/command/images.go
      linters:
        - lll
    - path: internal/config/config.go
      linters:
        - gocognit
    - path: internal/pouet/pouet.go
      linters:
        - tagliatelle
    - path: internal/zoo/zoo.go
      linters:
        - tagliatelle
    - path: internal/tags/tags.go
      linters:
        - gocyclo
        - gochecknoglobals
    - path: model/file_ansi_art.go
      linters:
        - dupl
    - path: model/file_bbs_adverts.go
      linters:
        - dupl
    - path: model/file_filepacks.go
      linters:
        - dupl
    - path: model/file_platforms.go
      linters:
        - dupl
    - path: model/file_text_files.go
      linters:
        - dupl
    - path: model/summary.go
      linters:
        - gocognit
        - maintidx
        - gocyclo
      
linters-settings:
  gomnd:
    # List of file patterns to exclude from analysis.
    # Values always ignored: `.+_test.go`
    # Default: []
    ignored-files: # magic number false positives.
      - 'milestone.go'
      - 'interview.go'
      - 'zoo.go'      
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    # Default is to use a neutral variety of English.
    locale: US
    # Default: []
    ignore-words:
      - 'Teh' # Teh Scene.
