# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate.
    # go generate breaks github actions.
    #- go generate ./...
builds:
  - id: server_dev
    binary: server
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64
      - darwin_amd64
      - windows_amd64
  - id: server
    binary: server
    env:
      - CGO_ENABLED=0
    goos: ['linux']
    goarch: ['amd64']
universal_binaries:
  - replace: true
    ids: ['server_dev']
archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: deb
    builds: ['server']
    package_name: df2-server
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Defacto2
    homepage: https://github.com/Defacto2/server
    maintainer: Ben Garrett <contact@defacto2.net>
    description: |-
      Defacto2 web server installer package.
    license: Copyright
    formats:
      - deb
    dependencies:
      - git
    bindir: /~/bin # install to user home so it doesn't require root access.

