# The Defacto2 server GoReleaser configuration.
#
# This releaser file is intended for the docker-compose.yml file
# to generate a release build of the server for Linux.
#
# The documentation is at https://goreleaser.com.
# To test any modifications to this configuration:
# goreleaser check
# goreleaser release --rm-dist --snapshot
# goreleaser build --rm-dist --snapshot
project_name: df2-server
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: server
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
archives:
  - format: zip
    name_template: >-
      {{ tolower .ProjectName }}_{{ .Version }}_{{- tolower .Os }}
    files:
      - src: public/text/defacto2.txt
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tmp:'
