# SQLBoiler configuration file
# see: https://pgloader.readthedocs.io
# quick guide: https://thedevelopercafe.com/articles/sql-in-go-with-sqlboiler-ac8efc4c5cb8
#
# recreate the static database ORM: sqlboiler psql --add-global-variants

# Target directory.
output = "postgres/models" 

# This should always be kept to true.
wipe = true

# Postgres database connection.
[psql]
dbname = "defacto2-ps"
host = "localhost"
pass = "example"
port = 5432
schema = "public"
sslmode = "disable"
user = "root"

[auto-columns]
created = "createdat"
updated = "updatedat"
deleted = "deletedat"

# MySQL database connection.
[mysql]
dbname = "defacto2-inno"
host = "localhost"
pass = "example"
port = 3306
sslmode = "false"
user = "root"
