version: '3'
#
# A placeholder container for the database migration and server.
# Intended for the domain test.defacto2.net.
#
services:

  webapp:
    container_name: defacto2-webapp
    restart: unless-stopped
    
    # build gets run using the --build flag or build command
    build:
      context: .      # use the current directory for the build context
                      # an inline dockerfile can be used instead of a Dockerfile
      dockerfile_inline: |
        FROM alpine:latest
        RUN mkdir /root/.config
        COPY dist/server_linux_amd64_v1/df2-server /usr/local/bin/df2-server
        EXPOSE 1323
        ENTRYPOINT ["df2-server"]

    ports:
      - "1323:1323"   # HTTP (unencrypted) port that the server listens on

    environment:
      - PS_HOST=localhost # this value must be kept as host.docker.internal 
                          # otherwise the server will not be able to connect 
                          # to the docker containerized postgres database

    extra_hosts:
      - "host.docker.internal:host-gateway" # this is required for the server to connect
                                            # to the docker containerized postgres database

# other services to add?
# dns_search:
# domainname: test.defacto2.net