module github.com/Defacto2/server

go 1.25.5 // latest: https://go.dev/dl/

// INFO: Usage of the packages
// Defacto2/ named packages are all internal but kept out of the main application.
// aarondl/ packages are for sqlboiler and is used for interacting with the database.
// bengarrett/bbs handles bbs color encoding text conversions.
// caarlos0/env simplifies the handling of operating system environment variables.
// carlmjohnson/versioninfo parses the Go version information.
// dustin/go-humanize is only used for two funcs, humanize.bytes and humanize.comma.
// friendsofgo/errors is used by the go packages generated by sqlboiler.
// gomarkdown is markdown parser and html renderer for the /public/md/ files.
// google/uuid is used as UUID validation for records in the database.
// gorilla/sessions is for the login and sign-ins for the website editor accounts.
// h2non/filetype is only used once, it displays the file mime type when editing an artifact record.
// jackc/pgx is an optimized PostgreSQL driver.
// labstack/echo is the web framework and http router.
// lmittmanm/tint colors the slog output.
// mattn/go-isatty checks if the io writer is a terminal.
// nalgeon/be is a simple testing package.
// rosedblabs/rosedb acts is in use as a cache for key/value stored data.
// samber/slog-multi permits the writing of a single slog record to multiple writers.
// subpop/go-ini parses ini settings syntax that is used by the jdos emulation.
// urface/cli is used with the flags package for command line interactions.
//
require (
	github.com/Defacto2/archive v1.1.4
	github.com/Defacto2/helper v1.6.5
	github.com/Defacto2/magicnumber v1.2.1
	github.com/Defacto2/releaser v1.3.20
	github.com/aarondl/null/v8 v8.1.3
	github.com/aarondl/sqlboiler/v4 v4.19.7
	github.com/aarondl/strmangle v0.0.9
	github.com/bengarrett/ansibump v1.1.0
	github.com/bengarrett/bbs v1.0.6
	github.com/bengarrett/binbump v1.0.0
	github.com/bengarrett/sauce v1.2.4
	github.com/caarlos0/env/v11 v11.3.1
	github.com/carlmjohnson/versioninfo v0.22.5
	github.com/dustin/go-humanize v1.0.1
	github.com/friendsofgo/errors v0.9.2
	github.com/gomarkdown/markdown v0.0.0-20250810172220-2e2c11897d1a
	github.com/google/uuid v1.6.0
	github.com/gorilla/sessions v1.4.0
	github.com/h2non/filetype v1.1.3
	github.com/jackc/pgx/v5 v5.8.0
	github.com/labstack/echo-contrib v0.17.3
	github.com/labstack/echo/v4 v4.14.0
	github.com/lmittmann/tint v1.1.2
	github.com/mattn/go-isatty v0.0.20
	github.com/nalgeon/be v0.3.0
	github.com/rosedblabs/rosedb/v2 v2.4.0
	github.com/samber/slog-multi v1.7.0
	github.com/subpop/go-ini v0.1.5
	github.com/urfave/cli/v2 v2.27.7
	golang.org/x/image v0.35.0
	golang.org/x/text v0.33.0
	google.golang.org/api v0.260.0
)

// Uncomment to use the local repository
//	replace github.com/Defacto2/archive => ../archive
//	replace github.com/Defacto2/helper => ../helper
//	replace github.com/Defacto2/magicnumber => ../magicnumber
//	replace github.com/Defacto2/releaser => ../releaser
//	replace github.com/bengarrett/ansibump => ../ansibump
//	replace github.com/bengarrett/sauce => ../sauce
//	replace github.com/bengarrett/binbump => ../binbump

require (
	cloud.google.com/go/auth v0.18.0 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.8 // indirect
	cloud.google.com/go/compute/metadata v0.9.0 // indirect
	dario.cat/mergo v1.0.2 // indirect
	github.com/aarondl/inflect v0.0.2 // indirect
	github.com/aarondl/randomize v0.0.2 // indirect
	github.com/air-verse/air v1.64.0 // indirect
	github.com/bep/godartsass/v2 v2.5.0 // indirect
	github.com/bep/golibsass v1.2.0 // indirect
	github.com/bwmarrin/snowflake v0.3.0 // indirect
	github.com/cpuguy83/go-md2man/v2 v2.0.7 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/fatih/color v1.18.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/fsnotify/fsnotify v1.9.0 // indirect
	github.com/go-logr/logr v1.4.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/gobwas/glob v0.2.3 // indirect
	github.com/gofrs/flock v0.12.1 // indirect
	github.com/gofrs/uuid v4.4.0+incompatible // indirect
	github.com/gohugoio/hugo v0.149.1 // indirect
	github.com/google/btree v1.1.3 // indirect
	github.com/google/go-cmp v0.7.0 // indirect
	github.com/google/licensecheck v0.3.1 // indirect
	github.com/google/s2a-go v0.1.9 // indirect
	github.com/google/safehtml v0.1.0 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.9 // indirect
	github.com/googleapis/gax-go/v2 v2.16.0 // indirect
	github.com/gorilla/context v1.1.2 // indirect
	github.com/gorilla/securecookie v1.1.2 // indirect
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761 // indirect
	github.com/jackc/puddle/v2 v2.2.2 // indirect
	github.com/klauspost/compress v1.18.0 // indirect
	github.com/labstack/gommon v0.4.2 // indirect
	github.com/mattn/go-colorable v0.1.14 // indirect
	github.com/pelletier/go-toml v1.9.5 // indirect
	github.com/pelletier/go-toml/v2 v2.2.4 // indirect
	github.com/robfig/cron/v3 v3.0.1 // indirect
	github.com/rosedblabs/wal v1.3.8 // indirect
	github.com/russross/blackfriday/v2 v2.1.0 // indirect
	github.com/samber/lo v1.52.0 // indirect
	github.com/samber/slog-common v0.19.0 // indirect
	github.com/spf13/afero v1.14.0 // indirect
	github.com/spf13/cast v1.10.0 // indirect
	github.com/tdewolff/parse/v2 v2.8.3 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v1.2.2 // indirect
	github.com/xrash/smetrics v0.0.0-20250705151800-55b8f293f342 // indirect
	go.opentelemetry.io/auto/sdk v1.2.1 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.63.0 // indirect
	go.opentelemetry.io/otel v1.38.0 // indirect
	go.opentelemetry.io/otel/metric v1.38.0 // indirect
	go.opentelemetry.io/otel/trace v1.38.0 // indirect
	go.uber.org/nilaway v0.0.0-20251208195206-89df5f7e6199 // indirect
	golang.org/x/crypto v0.47.0 // indirect
	golang.org/x/mod v0.32.0 // indirect
	golang.org/x/net v0.49.0 // indirect
	golang.org/x/oauth2 v0.34.0 // indirect
	golang.org/x/pkgsite v0.0.0-20260116214158-550788255d99 // indirect
	golang.org/x/sync v0.19.0 // indirect
	golang.org/x/sys v0.40.0 // indirect
	golang.org/x/time v0.14.0 // indirect
	golang.org/x/tools v0.41.0 // indirect
	golang.org/x/xerrors v0.0.0-20240903120638-7835f813f4da // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20251222181119-0a764e51fe1b // indirect
	google.golang.org/grpc v1.78.0 // indirect
	google.golang.org/protobuf v1.36.11 // indirect
	mvdan.cc/gofumpt v0.9.2 // indirect
	rsc.io/markdown v0.0.0-20241212154241-6bf72452917f // indirect
)

// air-verse/air is used by the serve and server tasks for live reloading.
// nilaway is a diagnostic tool to look for potential panics.
// pkgsite is used to run the website Go documentation using a localhost.
// gofumpt is a source code formatter.

tool (
	github.com/air-verse/air
	go.uber.org/nilaway/cmd/nilaway
	golang.org/x/pkgsite/cmd/pkgsite
	mvdan.cc/gofumpt
)
