// The Defacto2 web application built in 2023 on Go.
// (c) 2023 Ben Garrett.
// https://defacto2.net
package main

import (
	"embed"
	"os"
	"runtime"

	"github.com/Defacto2/server/cmd"
	"github.com/Defacto2/server/handler"
	"github.com/Defacto2/server/pkg/config"
	"github.com/Defacto2/server/pkg/logger"
	"github.com/Defacto2/server/pkg/postgres"
	"github.com/caarlos0/env/v7"
	_ "github.com/lib/pq"
)

//go:embed public/text/defacto2.txt
var brand []byte

//go:embed public/css/*
var css embed.FS

//go:embed public/images/*
var images embed.FS

//go:embed public/js/*
var js embed.FS

//go:embed public/**/*
var public embed.FS

//go:embed view/**/*.html
var views embed.FS

// version generated by GoReleaser ldflags
var version string

func main() {
	// Logger (use the development log until the environment vars are parsed)
	log := logger.Development().Sugar()

	// Environment configuration
	configs := config.Config{
		// hardcoded overrides can go here
		// IsProduction: true,
	}
	if err := env.Parse(
		&configs, env.Options{Prefix: config.EnvPrefix}); err != nil {
		log.Fatalf("Environment variable probably contains an invalid value: %s.", err)
	}

	// Command-line arguments
	// By default the web server runs when no arguments are provided
	const exitProgram = 0
	if code, err := cmd.Run(version, &configs); err != nil {
		log.Errorf("The command given did not work: %s.", err)
		os.Exit(code)
	} else if code >= exitProgram {
		os.Exit(code)
	}

	// Go runtime customizations
	if i := configs.MaxProcs; i > 0 {
		runtime.GOMAXPROCS(int(i))
	}

	// Setup the logger
	switch configs.IsProduction {
	case true:
		if err := configs.LogStorage(); err != nil {
			log.Fatalf("The server cannot save any logs: %s.", err)
		}
		log = logger.Production(configs.LogDir).Sugar()
	default:
		log.Debug("The server is running in the development mode.")
	}

	// Configuration sanity checks
	configs.Checks(log)

	// Database
	db, err := postgres.ConnectDB()
	if err != nil {
		log.Errorf("Could not connect to the database: %s.", err)
	}
	defer db.Close()

	// Cached global vars will go here to avoid the garbage collection.
	// They should be lockable.

	// Echo router/controller instance
	server := handler.Configuration{
		Import:  &configs,
		Log:     log,
		Brand:   &brand,
		Version: version,
		CSS:     css,
		Images:  images,
		JS:      js,
		Views:   views,
		Public:  public,
	}
	e := server.Controller()

	// Start the HTTP server
	go server.StartHTTP(e)

	// Gracefully shutdown the HTTP server
	server.ShutdownHTTP(e)
}
