// Package initialism provides a list of alternative spellings, acronyms and initialisms for the named releasers.
//
// Alternative spellings are the same name but with different casing, spelling or punctuation (e.g. Coca-Cola, Coke).
//
// An acronym is an abbreviation formed from the initial letters of other words and pronounced as a word (e.g. NATO).
//
// An initialism is an abbreviation consisting of the initial letters pronounced individually (e.g. USA).
package initialism

import (
	"maps"
	"slices"
	"strings"
)

// A Path is the partial URL path of the releaser.
type Path string

// List is a map of initialisms to releasers.
type List map[Path][]string

// path keys that are too long for the initialism map.
const (
	cpc2001 = "corporation-for-public-cybercasting-2001"
	core    = "complete-obliteration-of-retail-enforcement"
	crue    = "cheat-requests-for-the-underground-elite"
	epix    = "empire-of-pirate-intelligence-and-experts"
	mash    = "microcomputer-assembly-software-hackers"
	nappa   = "north-american-pirate_phreak-association"
	neua    = "national-elite-underground-alliance"
	nuaa    = "national-underground-application-alliance"
	iirg    = "international-information-retrieval-guild"
	jest    = "jolly-good-elites-traders-and-suppliers"
	tlf     = "tristar-ampersand-red-sector-inc*lightforce*fusion"
	assign  = "all-softwares-spread-into-global-network"
	mgsci   = "monthly-gameboy-scene-charts-international"
	nasa    = "north-american-society-of-anarchists"
	nnan    = "national-network-of-anarchists-and-nihilists"
	quick   = "quality-underground-image-creation-kings"
	rampage = "revolutionary-art-masters-pummeling-art-groups-everywhere"
	scud    = "sound-creators-and-unfailing-digitalizers"
	hate    = "highly-artistically-talented-enterprises"
	tsep    = "twilight-software-engineering-and-pirating"
	mcsci   = "monthly-console-scene-charts-international"
	nwo     = "new-world-order-computer-underground-magazine"
	uart    = "ultimate-association-of-reckless-talent"
)

const (
	ace = "ACE"
	ags = "AGS"
	cia = "CIA"
	cls = "CLS"
	cnc = "CNC"
	doa = "DOA"
	dst = "DST"
	dtc = "DTC"
	inf = "INF"
	mad = "MAD"
	rzr = "RZR"
	tca = "TCA"
	tcc = "TCC"
	tpc = "TPC"
	trs = "TRS"
	unt = "UNT"
)

const (
	inc   = "International Network of Crackers"
	razor = "Razor"
)

// Initialisms returns the list of initialisms.
//
// All initialisms should be in their stylized form and can include
// initialisms, acronyms, alternative spellings.
//
//   - Any casing and formatting should *not* be done here, those go in the [releaser/name] package.
//   - This is a public repo so commonsense problematic named groups or initialisms should not be listed.
//   - In Go, the order of the List map keys is randomized and has no performance impact.
//
// [releaser/name]: https://github.com/Defacto2/releaser/name
func Initialisms() *List { //nolint:maintidx
	list := List{
		"elite-leisure-files-bbs":               {"ELF"},
		"xquizit-ftp":                           {"xqz"},
		"watch-tower-ftp":                       {"wt"},
		"wolves-house-ftp":                      {"twh"},
		"silly-symphonies-ftp":                  {"ss"},
		"ambiquous-ftp":                         {"ambiq", "amb"},
		"camelot-ftp":                           {"cam"},
		"dafat-ftp":                             {"df", "da fat"},
		"dreamland-ftp":                         {"dl"},
		"false-hood-ftp":                        {"fh", "falsehood"},
		"primary-link-ftp":                      {"pl"},
		"quadcon-ftp":                           {"qc", "quad"},
		"rock-ftp":                              {"tr"},
		"nukers-database":                       {"nDB"},
		"software-distribution-corporation":     {"SDC"},
		"sons-of-boredom":                       {"SOB"},
		"lousy-old-loops":                       {"lool"},
		"doomsday-machines":                     {"DDM"},
		"devious-dezigns":                       {"DVS"},
		"faction-amiga":                         {"FTN"},
		"highlight":                             {"HL"},
		"highlight-ampersand-resistance-inc":    {"HLRI"},
		"hotstuffers":                           {"HTS"},
		"necropedophillic-anti_social-imbecils": {"NAI"},
		"avantgarde":                            {"AVT"},
		"stealth-force":                         {"TSF"},
		"rpm-bbs":                               {"Revolutions Per Minute BBS", "R.P.M BBS"},
		"swat":                                  {"Special Warez Acquisition Team", "S.W.A.T"},
		"cloud-nine-elite-bbs":                  {"Cloud 9 Elite BBS"},
		"phunline-bbs":                          {"The Phun Line BBS"},
		"nevada-testing-grounds-bbs":            {"NTG BBS"},
		"paladium-bbs":                          {"The Paladium BBS"},
		"devils-realm-bbs":                      {"The Devil's Realm BBS"},
		"penthouse-bbs":                         {"The Penthouse BBS"},
		"wild-side-bbs":                         {"The Wild Side"},
		"four-past-midnight-bbs":                {"4PM BBS", "FPM BBS"},
		"banished-corrosive-poison-bbs":         {"BCP BBS", "BNP BBS"},
		"lost-souls-domain-ii-bbs":              {"Lost Souls Domain 2 BBS", "LSD2 BBS", "LSDII BBS"},
		"marauders-hideout-bbs":                 {"THM BBS", "The Marauder's Hideout BBS"},
		"brotherhood-of-thieves-bbs":            {"BOT BBS"},
		"harmony-skates-bbs":                    {"SK8 BBS", "Harmony SK8 BBS"},
		"icepack":                               {"iCE PACK", "iCE Trial", "ITR", "ICEPK"},
		"art-creation-enterprise":               {ace, "ACE Productions", "A.C.E."},
		"underground-oasis-bbs":                 {"TUGO", "The Underground Oasis BBS"},
		"skill":                                 {"SKiLL/iCE Trial", "SKL", "BARQ"},
		"insane-creators-enterprise": {
			"iCE", "iCE Advertisements", "The New Order",
			"TNO", "iCE/TNO", "iCE Trial",
		},
		"insanity-corporate-network":             {"iCN", "iNSANITY"},
		"peoples-front-of-judea-bbs":             {"The Peoples Front of Judea BBS", "The PFJ BBS"},
		"programmers-inn-bbs":                    {"Programmer's Inn BBS"},
		"coliseum-bbs":                           {"Colisevm BBS"},
		"unknown-bbs":                            {"The Unknown BBS"},
		"final-frontier-bbs":                     {"The Final Frontier BBS", "TFF"},
		"warzone-bbs":                            {"The Warzone BBS", "The War Zone BBS"},
		"franks-palace-bbs":                      {"Frank's BBS", "Frank's Palace BBS"},
		"dragons-hold-bbs":                       {"The Dragon's Hold BBS"},
		"ghostship-bbs":                          {"The Ghostship BBS"},
		"deliberate-meltdown-bbs":                {"PMA WHQ BBS"},
		"euphoria-bbs":                           {"EU4iA"},
		"silo-bbs":                               {"The Silo BBS"},
		"midnight-oil-bbs":                       {"Mid-Nite-Oil BBS", "The Mid Nite Oil BBS", "Mid-Nite Oil BBS"},
		"hamburger-heavan-bbs":                   {"Hamburger Heaven BBS"},
		"frayed-ends-of-sanity-bbs":              {"TFEoS", "The Frayed Ends Of Sanity BBS"},
		"source-bbs":                             {"The Source BBS"},
		"maniac-bbs":                             {"The Maniac BBS"},
		"citadel-bbs":                            {"The Citadel BBS"},
		"untouchables-bbs":                       {"The Untouchables BBS"},
		"undiscovered-bbs":                       {"The Undiscovered BBS"},
		"xtc-systems-bbs":                        {"X-T-C System BBS", "XTC"},
		"ace-bbs":                                {"A.C.E BBS"},
		"abyss-bbs":                              {"The Abyss BBS"},
		"ravers-zone-bbs":                        {"The Raver's Zone BBS"},
		"hms-bounty-bbs":                         {"H.M.S. Bounty BBS"},
		"demons-forge-ca-bbs":                    {"Demon's Forge CA BBS"},
		"digital-underground-bbs":                {"The Digital Underground BBS", "TDU BBS"},
		"state-of-devolution-bbs":                {"Devoltion BBS"},
		"wall-bbs":                               {"The Wall BBS"},
		"citadel-of-chaos-bbs":                   {"COC BBS"},
		"cyberdyne-systems-bbs":                  {"CDS BBS"},
		"fatal-future-bbs":                       {"FF BBS"},
		"candyland-bbs":                          {"Candy Land BBS"},
		"circle_city-bbs":                        {"The Circle-City BBS"},
		"warp-speed-bbs":                         {"Warp Speed I BBS", "Warp Speed II BBS"},
		"celestial-woodlands-bbs":                {"The Celestial Woodlands BBS", "C. Woodlands BBS"},
		"bog-bbs":                                {"The Bog BBS"},
		"ethereal-dimension-bbs":                 {"The Ethereal Dimension BBS"},
		"rogues-gallery-bbs":                     {"Rogues' Gallery Bulletin Board System"},
		"warehouse-bbs":                          {"The Warehouse BBS", "TWH BBS"},
		"neutral-zone-bbs":                       {"The Neutral Zone BBS"},
		"viper-pit-bbs":                          {"The Viper Pit BBS"},
		"festering-pit-of-vile-excretions-bbs":   {"The Festering Pit BBS"},
		"boners-domain-bbs":                      {"The Boner's Domain BBS"},
		"circuits-edge-bbs":                      {"The Circuits Edge BBS"},
		"darkside-bbs":                           {"The Darkside BBS"},
		"pirate-bbs":                             {"The Pirate BBS"},
		"warez-houze-bbs":                        {"The Warez Houze BBS", "WaREZ HouZE Super System BBS"},
		"support-hq-bbs":                         {"The Support HQ BBS", "SHQ BBS"},
		"solar-system-bbs":                       {"Solar BBS"},
		"sanitarium-bbs":                         {"The Sanitarium BBS"},
		"rush-bbs":                               {"The Rush BBS"},
		"rock-creek-bbs":                         {"The RockCreek BBS"},
		"private-collection-bbs":                 {"The Private Collection BBS", "TPC BBS"},
		"notice-bbs":                             {"The Notice BBS"},
		"next-dimension-bbs":                     {"TND BBS", "The Next Dimension BBS"},
		"menace-ii-society-bbs":                  {"M2S BBS", "Menace 2 Society BBS"},
		"atlanta-pcug-bbs":                       {"Atlanta IBM-PCUG BBS", "Atlanta IBM PC User Group"},
		"board-bbs":                              {"The Board BBS"},
		"cauldron-bbs":                           {"The Cauldron BBS"},
		"apocalypse-bbs":                         {"The Apocalypse BBS"},
		"spyrits-crypt-bbs":                      {"Spyrit's Crypt BBS"},
		"slave-den-bbs":                          {"The Slave Den BBS"},
		"software-gallery-bbs":                   {"TSG BBS", "The Software Gallery BBS"},
		"razors-edge-bbs":                        {"The Razor's Edge BBS"},
		"carrier-of-belief-bbs":                  {"COB BBS"},
		"red-or-dead-bbs":                        {"ROD BBS"},
		"outer-limits-bbs":                       {"The Outer Limits BBS"},
		"northern-palace-bbs":                    {"The Northern Palace BBS"},
		"killer-town-bbs":                        {"Killertown BBS"},
		"junction-bbs":                           {"The Junction BBS"},
		"hell-hole-bbs":                          {"HellHole BBS"},
		"elusive-dreams-bbs":                     {"The Elusive Dream BBS"},
		"deadline-bbs":                           {"The Deadline BBS"},
		"dark-society-bbs":                       {"TDS BBS", "The Dark Society BBS"},
		"cloak-n-dagger-bbs":                     {"Cloak & Dagger BBS", "Cloak -N- Dagger BBS"},
		"crusades-bbs":                           {"The Crusades BBS"},
		"maximum-rocknroll-bbs":                  {"Maximum Rock'n Roll BBS", "Maximum Rock Roll BBS"},
		"marines-bbs":                            {"The Marines BBS", "TMB"},
		"chillout-zone-bbs":                      {"The Chillout Zone BBS"},
		"agents-of-fortune-bbs":                  {"AOF BBS", "ÆOF BBS"},
		"manhattan-project-bbs":                  {"The Manhattan Project BBS"},
		"last-resort-bbs":                        {"The Last Resort BBS"},
		"fate-gate-bbs":                          {"Fategate BBS", "FG BBS"},
		"dark-realm-bbs":                         {"The Dark Realm BBS", "TDR BBS"},
		"pleasure-dome-bbs":                      {"The Pleasure Dome BBS"},
		"pentagon-bbs":                           {"The Pentagon BBS", "PTG BBS"},
		"freeside-bbs":                           {"Fastjack's Freeside BBS", "FS BBS"},
		"beyond-akira-bbs":                       {"Akira BBS", "Beyond BBS"},
		"park-central-bbs":                       {"PC BBS"},
		"digital-fringe-bbs":                     {"The Digital Fringe BBS"},
		"underworld-bbs":                         {"The Underworld BBS", "TUW BBS"},
		"asylum-bbs":                             {"The Asylum BBS", "ASYL BBS"},
		"sanctuary-bbs":                          {"The Sanctuary BBS", "Sanct BBS", "SANC BBS"},
		"retaliators-place-bbs":                  {"RPB", "Retaliator's Place BBS"},
		"void-bbs":                               {"The Void BBS"},
		"rusty-n-edies-bbs":                      {"Rusty n Edie's BBS"},
		"arcade-bbs":                             {"The Arcade BBS"},
		"hood-bbs":                               {"The Hood BBS"},
		"house-of-pain-bbs":                      {"HOP BBS", "THOP BBS"},
		"infinite-darkness-bbs":                  {"ID BBS"},
		"mirage-bbs":                             {"The Mirage BBS"},
		"insane-asylum-bbs":                      {"The Insane Asylum BBS", "TIA BBS"},
		"black-hole-bbs":                         {"The Black Hole BBS"},
		"badlands-bbs":                           {"The Badlands BBS"},
		"tower-of-sorcery-bbs":                   {"TOS BBS"},
		"tribe-bbs":                              {"The Tribe BBS"},
		"yard-bbs":                               {"The Yard BBS", "TY"},
		"pits-bbs":                               {"The Pits BBS", "The P.I.T.S. BBS"},
		"world-of-elite-bbs":                     {"WOE"},
		"international-software-alliance":        {"ISA"},
		"dark-side-alliance":                     {"DSA"},
		"angels-on-drugs":                        {"AOD"},
		"endreamz":                               {"EDM"},
		"wad":                                    {"Wad Crew", "WADiSO"},
		"sos-iso":                                {"SoSiSO", "SoSFXP", "SoSFXP ISO"},
		"icoiso":                                 {"Independent Couriers Of iSO"},
		"sharper-image":                          {"SI"},
		"warez-without-limits":                   {"WWL"},
		"playmagic":                              {"PLY"},
		"free-trade-fxp":                         {"FTFiSO", "FTF"},
		"parents-on-puterz":                      {"POP"},
		"only-the-finest-warez":                  {"OTFW"},
		"drift":                                  {"Drift'ers", "DRiFTers"},
		"slow-trading-droopz":                    {"STD"},
		"wasteland-ftp":                          {"TWL", "The Wasteland FTP"},
		"v_i_b_e_s":                              {"VBS", "VIBES"},
		"intel":                                  {"International Nocturnal Team of Elite Loaders"},
		"compress-da-audio":                      {"CDA", "Compress 'da Audio"},
		"bleachbox-ftp":                          {"BBX"},
		"numbers":                                {"The Numbers", "*NuMbErS*", "NUM"},
		"the-warez-loop":                         {"The Warez Report", "MindBenders Report"},
		"zczi":                                   {"SCSI", "sc2i"},
		"msftug":                                 {"More shit from the underground"},
		"mortality":                              {"MTY"},
		"internet-relay-network":                 {"IRN"},
		"inner-circle":                           {"IC"},
		"generation-x":                           {"gen-x", "GNX"},
		"eclipse-interactive":                    {"EPI"},
		"darkside-couriers":                      {"DSC"},
		"assimilation":                           {"ASM"},
		"cellblock-4":                            {"CB4"},
		"majik":                                  {"MJK"},
		"masters-of-destruction":                 {"MOD"},
		"fuck-off-or-die":                        {"FOOD"},
		"digital-corruption":                     {"DC"},
		"crc":                                    {"CoRRuPTiON"},
		"swift-couriering-inc":                   {"SCI"},
		"ians-rotting-corpse":                    {"IRC"},
		"lords-of-chaos":                         {"LoC"},
		"malfunction-system-group":               {"MfSG"},
		"elite-underground":                      {"EU"},
		"anarchy-and-armageddon-network":         {"AAA"},
		"andromeda-software-development":         {"ASD"},
		"black-widow":                            {"BLW"},
		"united-artists-association":             {"UAA"},
		"italian-cracking-service":               {"ICS"},
		"ddd":                                    {"D.D.D.", "Dr. Death / Darkhawk"},
		"echo-mirage":                            {"EM"},
		"elite-programmers-association":          {"EPA"},
		"casa":                                   {"California Sysop Association"},
		"union-of-crackers":                      {"UoC"},
		"game_busters":                           {"BlackMax's Gamebusters Inc."},
		"bad-association":                        {"BBS's Against Dweebs"},
		"west-coast-alliance":                    {"WCA"},
		"warriors-against-copy-protection":       {"WACP"},
		"the-alternative":                        {"An Alternative release", "Celerity"},
		"state-of-the-art":                       {"SOTA"},
		"boogie-down-productions":                {"BDP"},
		"digital-exchange-pirate-board-alliance": {"DEPBA"},
		"the-knights-of-the-round-table":         {"TKRT"},
		"sprint":                                 {"$PRINT"},
		"black-star-productions":                 {"B*P"},
		"the-billionarre-boys-club":              {"BBC", "Billionaire Boys Club"},
		"c-ampersand-m":                          {"C&M"},
		"united-file-traderz":                    {"UFT"},
		"european-trading-alliance":              {"ETA"},
		"best-of-the-best-phreaking-man":         {"BOB"},
		"hungarian-megacracker-group":            {"HMG"},
		"inter-active":                           {"IA"},
		"unreal-reality":                         {"UR"},
		"success-pc":                             {"SPC"},
		"the-primal-order":                       {"TPO"},
		"the-avocado-avengers":                   {"TAA"},
		"madras":                                 {mad},
		"mirth":                                  {"MTH"},
		"bs-enterprize":                          {"B.S. Enterprize"}, //nolint:misspell
		"osiris":                                 {"ORS"},
		"dark-force":                             {"DF"},
		"calculus":                               {"TCG", "The Calculus Group"},
		"distorted":                              {"DSD"},
		"cyanide":                                {"CYN"},
		"german-diskdoubler":                     {"GDD"},
		"un_touchable-force-organization":        {"UTFO"},
		"jackshit":                               {"jS"},
		"187":                                    {"187 Couriers", "One Eight Seven"},
		"banch-o-guyz":                           {"BOG"},
		"lamer-of-the-world":                     {"LOTW"},
		"hasp":                                   {"H.A.S.P."},
		"roi-production":                         {"ROI", "WaREZ ROI"},
		"indigo":                                 {"IGD"},
		"storm-inc":                              {"SM"},
		"syndrome":                               {"SYD"},
		"the-cracking-team":                      {"TCT"},
		uart:                                     {"UART", "URT"},
		"universal-crime-league":                 {"UCL"},
		"phase-one":                              {"P1"},
		"the-damaged-inc":                        {"TDi"},
		"undercover-agents":                      {"UA"},
		"atomic-review":                          {"ATM", "Atomic Review Krew"},
		"ironside-data-productions":              {"iDP"},
		"italian-crackware-inc":                  {"ICI"},
		"scd_dox":                                {"SCD", "Software Chronicles Digest / Dox Division"},
		"needful-things":                         {"NT"},
		"one-man-courier":                        {"OMC"},
		"no-bullshit-couriering":                 {"NBC"},
		"north-american-release-coalition":       {"NARC"},
		"dual-module-player":                     {"DMP"},
		"global-overdose":                        {"GOD"},
		"new-order":                              {"NO"},
		"butthole-surfers":                       {"BH"},
		"lightning-force":                        {"LF"},
		"psychosquad":                            {"PSD"},
		"rage-against-the-machine":               {"RAM"},
		"wankers-from-wimbledon":                 {"WW"},
		"mental-design":                          {"MD"},
		"jammin-the-airwaves":                    {"JTA"},
		"never-at-rest-couriers":                 {"NARC"},
		"siac":                                   {"SiÆC"},
		"syndicated-network-of-couriers":         {"SyNC"},
		"sliver-art-products":                    {"SAP"},
		"virtual-shock":                          {"VS"},
		"5th-dynasty":                            {"5D"},
		"paradigm-press":                         {"prdgm"},
		"corosion":                               {"COR"}, //nolint:misspell
		"warriors-against-software-protection":   {"WASP"},
		"no-lamerz-allowed":                      {"NLA"},
		"anoxia":                                 {"ANX"},
		"north-american-pirates":                 {"NAP"},
		"avengers":                               {"AVG"},
		"computer-pirate-syndicate":              {"CPS", "CP$"},
		"visual-simulations-inc":                 {"VSI"},
		"the-golden-triangle":                    {"TGT"},
		"the-newcomers":                          {"TNC"},
		"china-syndrome-inc":                     {"CSI"},
		"housetek":                               {"HTK"},
		"outlaws-exchange":                       {"OX"},
		"syndromes-mega-utility-team":            {"SMUT"},
		"entity":                                 {"ntt"},
		"ntt":                                    {"NTT"},
		"quick-silver":                           {"QSR", "QuickSilver"},
		"pyrodex":                                {"PRX", "Pyrodex PC Division"},
		"psychedelic-excretion-international":    {"PEi", "Psychdelic Excretion International"},
		"xtreemer":                               {"XT"},
		"top-curry-group":                        {"TCG"},
		"just-the-facts-handheld-edition":        {"JTF"},
		"weekly-wanking-stats":                   {"WWS"},
		"pocketheaven":                           {"PH"},
		"just-week-stats":                        {"JWS"},
		"some-weekly-chart":                      {"SWC"},
		"who-owned-weekly":                       {"WoW"},
		"the-marshall-mussolini-show":            {"TMMS"},
		"weekly-courier-stats-report":            {"WCSR"},
		"the-tobacco-brothers":                   {"TTBC"},
		"orgasming-gaming-magazine":              {"OGM", "ORGAS"},
		"monthly-cracking-report":                {"MCR"},
		"zero-second-report":                     {"0SR"},
		"unbiased-courier-report":                {"UCR"},
		"the-big-picture-courier-report":         {"TBP"},
		"prozacs-personal-gaming-report":         {"PPGR"},
		"gameboycolor-world-charts":              {"GBWC", "GBC World"},
		"dextrose-chart":                         {"DX"},
		"couriers-weekly":                        {"CW"},
		"corrupt-console-diskmag":                {"CORR"},
		"actual-factual-couring":                 {"AfC"},
		"frontline-scene-release-report":         {"FTL"},
		"future-scene-news":                      {"FSN"},
		"nuclear-crackers":                       {"NC"},
		nwo:                                      {"NWO"},
		"scene-top-traders":                      {"STT"},
		"weekly-courier-report":                  {"WCR"},
		"top-telnet-traders-weekly":              {"TTW"},
		"the-legendary-report":                   {"TLR"},
		"resistance":                             {"RSE"},
		mcsci:                                    {"MCSCI"},
		"zenith-zine":                            {"ZZ"},
		"canadian-born-coders":                   {"CBC"},
		"virus-laboratories-and-distribution":    {"VLAD"},
		"higher-mental-plane":                    {"hmp"},
		"dutch-trader-charts":                    {dtc},
		"bbs-and-users-digest":                   {"BAUD"},
		"trip-2-hell":                            {"T2h"},
		"strictly-pirates":                       {"SP", "SP!"},
		"software-runners-from-hell":             {"SRH"},
		"software-pirates-alliance":              {"SPA"},
		"rebels-of-telecommunications":           {"ROT"},
		"quality-control-reviews":                {"QC"},
		"evolution-magazine":                     {"EVO", "EVOL"},
		"digital-press":                          {"DP"},
		"bizarre-types-of-wares":                 {"BTW"},
		"underground-experts-united":             {"UXU"},
		"the-review-crew":                        {"TRC"},
		"poison-control":                         {"PCi"},
		"magick":                                 {"MGK", "MUDD", "M.U.D.D.", "Magick Utilities & Demo's Division"},
		"infinity-93":                            {inf},
		"foundation":                             {"FDN"},
		"thhg":                                   {"The Hugo Husten Group", "The Horrible Hackers from Germany"},
		"2000ad":                                 {"2KAD", "2000 AD"},
		"8088-state":                             {"8088"},
		"aces-of-ansi-art":                       {"AAA"},
		"acid-productions":                       {"ACiD", "ANSi Creators in Demand"},
		"addiction-in-releasing":                 {"AiR"},
		"advanced-art-of-cracking-group":         {"AAOCG"},
		"advanced-pirate-technology":             {"APT"},
		"advanced-software-accessories":          {"ASA", "Advantage Software Accessories"},
		"adrenalin":                              {"Adren"},
		"affinity":                               {"AFT"},
		"aegis-corp":                             {ags},
		"air":                                    {"Team AiR", "AiRISO"},
		"arkham":                                 {"AKM"},
		"alpha-flight":                           {"AFL"},
		"ages":                                   {ags},
		"against-software-protection":            {"ASP"},
		"aggression":                             {"ARN", ags},
		"amnesia":                                {"AMN"},
		"american-pirate-industries":             {"API"},
		"amplified-music-pirates":                {"AMP"},
		"anemia":                                 {"ANM"},
		"ansi-requires-talent":                   {"ART"},
		"anti-warez-association":                 {"AWA"},
		"anthrox":                                {"ATX", "AS"},
		"anti-security-agency":                   {"ASA"},
		"anti-lamers-foundation":                 {"ALF"},
		"anarchy-international-production":       {"AIP"},
		"ansi-factory":                           {"AFC"},
		assign:                                   {"ASSiGN"},
		"association-of-software-conspiracy":     {"ASC"},
		"astalavista-group":                      {"ASTA"},
		"arab-team-4-reverse-engineering":        {"AT4RE"},
		"arrogant-couriers-with-essays":          {ace},
		"art-of-reverse-engineering":             {"AORE"},
		"artists-in-revolt":                      {"AiR"},
		"argies-courier-united":                  {"ACU"},
		"atari-pirates-incorporated":             {"API"},
		"atlantic-trading-alliance":              {"ATA"},
		"attack-decay-sustain-release":           {"ADSR", "AR"},
		"artists-without-loyality":               {"AWoL"},
		"arcane-corporate-elite":                 {ace},
		"backlash":                               {"BLH"},
		"bad-ass-dudes":                          {"BAD"},
		"bad-news":                               {"BaD", "B.A.D. Newsletter", "The BAD News"},
		"baywatch":                               {"BWH"},
		"bentley-sidwell-productions":            {"BSP"},
		"belly-are-kiss-attack":                  {"BAKA"},
		"beverly-hills-boys":                     {"BHB"},
		"blades-of-steel":                        {"BOS", "Blades"},
		"black-out":                              {"BLOT"},
		"black-riders":                           {"BRD"},
		"black-squadron":                         {"BS"},
		"blaze":                                  {"BLZ"},
		"blizzard":                               {"BLZ", "blizz"},
		"blue-beta-3d":                           {"BB3D"},
		"bitchin-ansi-design":                    {"BAD"},
		"binaries":                               {"BiN"},
		"billionaire-boys-club":                  {"BBC"},
		"break-the-copyright":                    {"BTCR"},
		"brotherhood-of-warez":                   {"BOW"},
		"brotherhood-union":                      {"BHU"},
		"boys-from-company-c":                    {"BCC"},
		"bonzai":                                 {"BNZ"},
		"buds-biased-utils-report":               {"utils"},
		"bytegarden":                             {"BTG"},
		"canadian-pirates-inc":                   {"CPI"},
		"cancer":                                 {cnc},
		"car-e-lee":                              {"CEL"},
		"cascada":                                {"CDA"},
		"cardinals":                              {"CDS"},
		"cd-images-for-the-elite":                {"CiFE"},
		"celerity-utilities-division":            {"CUD"},
		crue:                                     {"CRUE"},
		"chaos":                                  {"CHS"},
		"class":                                  {cls},
		"classic":                                {cls},
		"classic-cracking-corporation":           {"CCC"},
		"club-elan":                              {"CE", "Club Elán"},
		"chaos-cyber-creations":                  {"CCC"},
		"chemical-reaction":                      {"CRO"},
		"chinese-software-distribution-network":  {"CSDN"},
		"codex":                                  {"CDX"},
		"coders-task-force":                      {"CTF"},
		"coolphat-vibez":                         {"CPHV"},
		"coop":                                   {"The Dream Team + Tristar + Red Sector Inc.", "The Co-op"},
		"community-of-moral-advancement":         {"COMA", "CMA"},
		"conspiracy":                             {"CSY", "CPY"},
		"contour":                                {"CTR"},
		"console-supply-iso":                     {"CSISO"},
		"console-gaming-informers":               {"CGI"},
		"copycats-inc":                           {"CCI"},
		"copyright-infiltration-agency":          {cia},
		"corruption":                             {"COR"},
		"corporate-graphics":                     {"CGX"},
		"corrupted-programming-international":    {"CPI"},
		"criminals-of-radical-extremes":          {"CORE"},
		core:                                     {"CORE"},
		cpc2001:                                  {"C.P.C. 2001", "CPC", "CPC 2001"},
		"couriers-of-pirated-software":           {"COPS"},
		"couriers-of-proven-software":            {"COPS"},
		"courier-weektop-scorecard":              {"CwS"},
		"couriers-of-darkness":                   {"COD"},
		"crack-report-weekly":                    {"CRW"},
		"cowboys-from-hell":                      {"CFH"},
		"crackers-and-hackers-anonymous":         {"CHA"},
		"crackers-in-action":                     {cia},
		"crackers-international-alliance":        {cia, "Crackers Int'l Alliance"},
		"crackpl":                                {"CP"},
		"crack-in-morocco":                       {"CiM"},
		"cracking-for-fun":                       {"CFF"},
		"cracking-101":                           {"C101"},
		"cracking-in-ocean":                      {"CiO"},
		"crackers-ampersand-whackers":            {"C&W", "CW"},
		"crazyworld":                             {"CZW"},
		"creeping-death-software":                {"CDS"},
		"crime-syndicate-net":                    {"TCS"},
		"crystal-phasematics":                    {"CPM"},
		"cryptonics-crew":                        {"CTC"},
		"texas-chainsaw-massacre-bbs":            {"TCM BBS"},
		"what-the-bbs":                           {"What The..?! BBS"},
		"creators-of-intense-art":                {cia},
		"covert-action-ii-bbs":                   {"Covert Action 2 BBS", "CA2 BBS"},
		"creators-of-revolutionary-pictures":     {"CORP", "CφRP", "CRP", "C.O.R.P"},
		"crude":                                  {"CRD"},
		"cti":                                    {"Crude & TDK iNC"},
		"cybrix":                                 {"CBX", "Cybrix Couriering"},
		"cygnus":                                 {"CYG"},
		"cybermail":                              {"CM"},
		"cyber-force":                            {"CF"},
		"cyber-legion":                           {"CL"},
		"cybercrime-international-network":       {"CCi", "CyberCrime Inc."},
		"darksiders":                             {"DS"},
		"da-breaker-crew":                        {"DBC"},
		"dbcdemo":                                {"DBC", "Da Breaker Crew Demo Division"},
		"dagger":                                 {"DGR"},
		"damage-incorporated":                    {"Di"},
		"damn-excellent-ansi-design":             {"DeAD"},
		"damn-excellent-ansi-designers":          {"DeAD"}, // Correct
		"darkside-incorporated":                  {"DSI"},
		"dark-towers-international":              {"DTI"},
		"delirium-tremens-group":                 {"DTG"},
		"dead-memory":                            {"DM"},
		"dead-on-arrival":                        {doa},
		"dead-pirates-society":                   {"DPS"},
		"decrepit-old-geezers":                   {"DOG"},
		"defacto":                                {"DF"},
		"defacto2":                               {"DF2", "DF"},
		"defacto2net":                            {"DF2"},
		"defiant":                                {"DFT"},
		"demented-dimensions":                    {"DD"},
		"delirium-of-disorder":                   {"DoD"},
		"demon-release-crew":                     {"DRC"},
		"desperate-turk-crackers":                {"Desperate", "DP"},
		"destined-masters-of-zines":              {"DMZ"},
		"digital-factory":                        {"DF"},
		"disciples-of-private-enterprise":        {"DOPE"},
		"disciples-of-the-dark-knight":           {"DDK"},
		"disire":                                 {"DSR"},
		"dead-weight":                            {"DW"},
		"dead-or-alive":                          {doa},
		"deviance":                               {"DEV", "DVN", "DVNiSO"},
		"divine":                                 {"DVN", "Divine Gods", "Divine ISO", "DVNISO", "DIVINEISO"},
		"dinobytes":                              {"DiNO-BYTES", "Dino Bytes"},
		"cadmium":                                {"cdm"},
		"phxiso":                                 {"Phoenix ISO"},
		"details":                                {"DTS"},
		"the-kennal-club":                        {"TKC", "KC"},
		"deviated":                               {"DVT"},
		"devotion":                               {"DEV", "devot"},
		"digerati":                               {"DGT"},
		"digital-artists-of-the-rare-kind":       {"DARK"},
		"digital-insanity":                       {"DI"},
		"digital-millennium-cracking-alliance":   {"DMCA"},
		"digital-noise-alliance":                 {"DNA"},
		"direct-from-stars":                      {"DFS"},
		"direction-simple-la-kamisole":           {"DSK"},
		"dimension":                              {"DMS"},
		"distinct":                               {dtc, "DTN"},
		"dislocated-babes":                       {dst},
		"disassemblers-of-america":               {doa},
		"distributors-of-classic-warez":          {"DCW"},
		"divide-by-zero":                         {"DBZ"},
		"domination-in-couriering":               {"DiC"},
		"downtown-hackers-crew":                  {"D.H Crew", "DHC"},
		"dreadloc":                               {"DLC"},
		"dream-team":                             {"DT"},
		"dream-syndicate":                        {"DS"},
		"drunken-rom-group":                      {"DRG", "Drunken"},
		"drone":                                  {"DRN"},
		"drink-or-die":                           {"DOD"},
		"dvt":                                    {"Devotion", "TeamDVT"},
		"deadly-underground-network-of-elites":   {"DUNE"},
		"dutch-computer-enterprise":              {"DCE"},
		"doc-writers-inc":                        {"DWI"},
		"dynasty":                                {"DYN", "DNS"},
		"same-shit-different-day":                {"SS-DD"},
		"dynamix":                                {"DNX"},
		"dytec":                                  {"DYT", dtc},
		"eagle-soft-incorporated":                {"ESI"},
		"ebola-virus-crew":                       {"EVC"},
		"eclipse":                                {"ECL"},
		"east-coast-connection":                  {"ECC"},
		"eximius":                                {"XMS"},
		"extasy":                                 {"EX"},
		"exodus-couriers":                        {"Exodus Couriering"},
		"elite-carding-network":                  {"ECN"},
		"empire-of-darkness":                     {"EOD"},
		"embrace":                                {"EMB"},
		"electro-magnetic-crackers":              {"EMC"},
		"electromotive-force":                    {"EMF"},
		"electronic-rats":                        {"ECR"},
		"empire":                                 {"EMP"},
		"emporio":                                {"EMP"},
		"end-of-file":                            {"EOF"},
		"energy":                                 {"NRG"},
		epix:                                     {"EPIX"},
		"equinox":                                {"EQX"},
		"esprit-couriers":                        {"Esprit"},
		"esp-pirates":                            {"ESP"},
		"eternity":                               {"ETE"},
		"eithel":                                 {"ETH"},
		"excess":                                 {"ECS"},
		"exceptional":                            {"XCP"},
		"excessive-force-crew":                   {"EFC"},
		"explosion":                              {"EPN"},
		"extinct":                                {"EX"},
		"extreme":                                {"EXT"},
		"extreme-team":                           {"ET"},
		"extreme-graphix-alliance":               {"XGA"},
		"exterminators":                          {"TEX"},
		"extreme-trading-crew":                   {"ETC"},
		"evidence":                               {"EVD"},
		"euphoria":                               {"EPH"},
		"fairlight":                              {"FLT"},
		"fairlight-dox":                          {"FDX", "FLTDOX", "FAIRDOX"},
		"faith":                                  {"FTH"},
		"fallen":                                 {"FLN"},
		"fatal":                                  {"FTL"},
		"fatbastards":                            {"FB"},
		"fantastic-4-cracking-group":             {"F4CG"},
		"fast-action-trading-elite":              {"fATE"},
		"faster-than-light-couriers":             {"FLC"},
		"fatigued-couriers-network":              {"FCN"},
		"federal-cracking-consortium":            {"FCC"},
		"fast-elite-distributors-of-software":    {"FEDS"},
		"fighting-for-fun":                       {"fff"},
		"fight-only-for-freedom":                 {"FOFF"},
		"file-rappers":                           {"FR"},
		"fistful-of-steel":                       {"FOS"},
		"five-o":                                 {"Five 0"},
		"flying-horse-cracking-force":            {"FHCF"},
		"free-on-the-line":                       {"FOTL"},
		"freelancers-guild":                      {"FRL"},
		"fucked-beyond-repair":                   {"FBR"},
		"future-crew":                            {"FC"},
		"future-brain-inc":                       {"FBi", "FBIA"},
		"futuristic-artists-with-talent":         {"FAT"},
		"fusion":                                 {"FSN"},
		"galactic-review":                        {"GALA"},
		"game-release-list":                      {"Releases by Claude Rains"},
		"grave-yard-crew":                        {"GYC"},
		"gencliq":                                {"GCT"},
		"german-cracking-group":                  {"GCG"},
		"german-consoles-syndicate":              {"GCS"},
		"german-trading-alliance":                {"GTA"},
		"german-warez-alliance":                  {"GWA"},
		"genesis-ppe":                            {"GNS"},
		"genesis":                                {"GNS"},
		"genesis-project":                        {"GP"},
		"guild-of-distributors":                  {"GODS", "GDS"},
		"glory":                                  {"Glory Couriers", "GL"},
		"god-damn-warez":                         {"GDW"},
		"gorgeous-ladies-of-warez":               {"GLOW", "GlowISO"},
		"hrps":                                   {"H.R. Puppystuff"},
		"the-free-loaders":                       {"TFL"},
		"heritage":                               {"HTG"},
		"gothic":                                 {"GTHC"},
		"goofy-illitape-softwarez":               {"GIS"},
		"graphic-revolution-in-progress":         {"GRiP"},
		"grand-old-pirates":                      {"GOP"},
		"elite-couriers-group":                   {"ECG"},
		"epsilon":                                {"EPS"},
		"fatal-connection":                       {"FC", "FATAL"},
		"fawkes":                                 {"FWK"},
		"fasiso":                                 {"FAS"},
		"file-propulsion-system":                 {"FPS"},
		"friendship":                             {"FRD", "Friends"},
		"federation-of-free-traders":             {"FOFT"},
		"fyllecell":                              {"FLC"},
		"future-ansi-creations":                  {"FAiC"},
		"graphically-enhanced-magazine":          {"GEM"},
		"glorious-console-master-race":           {"GCMR"},
		"ghost-riders":                           {"GRS"},
		"god-of-war":                             {"GOW"},
		"graphics-rendered-in-magnificence":      {"GRiM"},
		"gainseville-pirates-association":        {"GPA"},
		"hard-to-beat-team":                      {"HTB"},
		"hard-core-hackers":                      {"hCh"},
		"halcyon":                                {"HLN"},
		"hackers-with-attitude":                  {"HWA"},
		hate:                                     {"HaTe"},
		"hearts-in-the-shadows":                  {"HiTS"},
		"hardcore-elite-mother-phuckers":         {"HEMP", "HMP"},
		"haze":                                   {"HZ"},
		"highroad":                               {"HR"},
		"high-society":                           {"HS"},
		"high-voltage":                           {"HV", "HVC", "VOLT"},
		"high-speed-couriers":                    {"HSC"},
		"high-tech-couriers":                     {"HTC"},
		"high-speed-global-mass-trading":         {"HSGMT"},
		"hipe":                                   {"HPE"},
		"hoodlum":                                {"HLM"},
		"hooligans":                              {"HLG"},
		"horizon":                                {"HZN"},
		"humble-dox":                             {"The Humble Guys DOX"},
		"hummers":                                {"HUM"},
		"hybrid":                                 {"HBD"},
		"gobble":                                 {"GOB"},
		"grind":                                  {"GND"},
		"imperial-falcon":                        {"IF"},
		"the-unorginal-bastards":                 {"TUB"},
		"hysteria":                               {"HSA"},
		"hype":                                   {"HYP"},
		"keen-like-frogs":                        {"KLF"},
		"kryptonic-hacking-team":                 {"KHT"},
		"kalisto":                                {"KAL"},
		"krackass":                               {"KASS"},
		"katharsis":                              {"KTS"},
		"kosmic-loader-foundation":               {"KLF"},
		"knights-of-the-round-table":             {"KORT"},
		"kyrie-eleison":                          {"KE", "KEISO"},
		"kryn":                                   {"KRN"},
		"idiots-creations-unlimited":             {"iCU"},
		"illuminatus":                            {"ILL"},
		"illusion":                               {"iLL"},
		"infinity-e_mag":                         {inf},
		"ifranian-rebellious-hackers":            {"IRH"},
		iirg:                                     {"IIRG"},
		"immersion":                              {"IMS"},
		"independent":                            {"IND", "individual"},
		"independent-crackers-union":             {"ICU"},
		"independant-cracking-institute":         {"ICI", "Independent Cracking Institute"}, //nolint:misspell
		"indonesia-reversing-crew":               {"IRC"},
		"intension":                              {"ITN"},
		"international-ghost-hunters":            {"IGH"},
		"international-network-of-crackers":      {"INC"},
		"inc-europe":                             {"INC", inc},
		"international-cracking-crew":            {"iCC"},
		"inc-documentation-division":             {"IDD", inc},
		"inc-utility-division":                   {"IUD", inc},
		"interpol":                               {"IPL"},
		"image":                                  {"IMG"},
		"imphobia":                               {"IMP"},
		"impact":                                 {"IMP"},
		"influence":                              {"iNF"},
		"infinity":                               {inf},
		"infinity-trainers-unlimited":            {"ITU"},
		"information-liberation-league":          {"ILL"},
		"international-software-traders":         {"IST"},
		"insanity":                               {"Insan"},
		"inquisition":                            {"INQ"},
		"interceptor":                            {"INT"},
		"invisible":                              {"INV"},
		"iranian-crackers-association":           {"ICA"},
		"iridium-magazine":                       {"IRIDI"},
		"jrp":                                    {"JRP"},
		jest:                                     {"JEST"},
		"justiso":                                {"JI"},
		"just-for-fun":                           {"JFF", "J4F", "Just 4 Fun"},
		"just-for-phun":                          {"J4P"},
		"just-the-facts":                         {"JTF"},
		"lamers-of-power":                        {"LOP"},
		"lancelot":                               {"LANCE"},
		"lancelot-2":                             {"LANCE"},
		"llange-art-reptareeko":                  {"LAR"},
		"last-poets-society":                     {"LPS"},
		"laxity":                                 {"LXT"},
		"lethal-software-distributors":           {"LSD"},
		"legacy":                                 {"LGC", "LGY"},
		"legend":                                 {"LGD", "Legend PC", "PC/Legend"},
		"legends-never-die":                      {"LND"},
		"legion-of-doom":                         {"LOD", "LOH", "LOD/H"},
		"legion-of-dynamic-discord":              {"LODD"},
		"legion-of-rising-distributors":          {"LORD"},
		"inferno":                                {inf},
		"licensed-to-draw":                       {"LTD"},
		"little-big-one":                         {"LBO"},
		"light-speed-distributors":               {"LSD"},
		"light-speed-warez":                      {"LSW"},
		"lightforce":                             {"LFC", "LF"},
		"lithium":                                {"LIT"},
		"linezer0":                               {"LZ0", "LZO", "LineZero"},
		"live-now-die-later":                     {"LnDL"},
		"lockless":                               {"LKL"},
		"legion-of-the-etherial":                 {"LOTE"},
		"local-courier-system":                   {"LCS"},
		"living-organisms-on-mars":               {"LOOM"},
		"los-angeles-sysops-alliance":            {"LASA"},
		"lucid":                                  {"LCD"},
		"lucifer":                                {"LUC"},
		"mack-crack-corporation":                 {"MCC"},
		"masters-of-abstractions-and-illusions":  {"MAi"},
		"malicious-art-denomination":             {mad},
		"malondorous-griffin-entanglement":       {"MGE"},
		"malice":                                 {"MAL"},
		"majic-12":                               {"M12"},
		"magnificent-art-designers":              {mad},
		mash:                                     {"MASH"},
		"masters-of-the-art-experience":          {"MAX"},
		"masque":                                 {"MSQ"},
		"master-artists-guild-for-the-elite":     {"MAGE"},
		"mea-culpa":                              {"MC"},
		"medeival-emporium-of-warez":             {"MEOW"}, //nolint:misspell
		"menaceiisociety":                        {"MiiS"},
		"millenium":                              {"MnM", "MiLLENNiUM"}, //nolint:misspell
		"mutual-assured-destruction":             {mad},
		"manifest":                               {"MFD", "Manifest Destiny"},
		mgsci:                                    {"MGSCI"},
		"mercury":                                {"MERC"},
		"more-stupid-initials":                   {"MSI"},
		"motiv8":                                 {"M8"},
		"micropirates-inc":                       {"MPI"},
		"mickey-mouse-club":                      {"MMC"},
		"mirage":                                 {"MIR"},
		"miami-cracking-machine":                 {"MCM"},
		"mindcrash":                              {"MC"},
		"modders-on-drugs":                       {"MOD"},
		"myth-inc":                               {"M.Y.T.H. Inc", "MYTH Inc Link BBS"},
		"myth*deviance":                          {"MDVN"},
		"myth":                                   {"MYT"},
		"nah-kolor":                              {"NAH"},
		neua:                                     {"NEUA", "North Eastern Underground Alliance"},
		nuaa:                                     {"NUAA"},
		"napalm":                                 {"NPM"},
		"national-crackers-alliance":             {"NCA"},
		"national-distribution-network":          {"NDN"},
		nnan:                                     {"NNAN"},
		"nerve":                                  {"NRV"},
		"netrunners":                             {"NR"},
		"network-software-association":           {"NSA"},
		"new-york-crackers":                      {"NYC"},
		"new-world-order":                        {"NWO"},
		"nexus":                                  {"NXS", "NX"},
		"nemesis":                                {"NMS"},
		"nokturnal-trading-alliance":             {"NTA"},
		"no-fear":                                {"NF"},
		"noobs-reverser-team":                    {"NBR"},
		"nordic-engineering-corporation":         {"NEC"},
		"north-eastern-crackers":                 {"NEC"},
		nappa:                                    {"NAPPA", "NAP/PA", "NAPE"},
		"nintendo-backup-crew":                   {"NBC"},
		"nrp":                                    {"NRP"},
		nasa:                                     {"NASA"},
		"nc_17":                                  {"NC"},
		"national-software-network":              {"NSN"},
		"norwegian-cracking-company":             {"NCC"},
		"noclass":                                {"NoCLS", cls},
		"not-productions":                        {"NOT!"},
		"objectile":                              {"OCT"},
		"oceanine":                               {"OCN"},
		"oddity":                                 {"ODT"},
		"old-warez-inc":                          {"OWI", "OldWarez Inc"},
		"oldskool":                               {"OS"},
		"old-school-pirates":                     {"OSP"},
		"oneup":                                  {"1UP", "One Up"},
		"on_line-revenge":                        {"OLR", "Online Revenge"},
		"orion":                                  {"ORN"},
		"origin":                                 {"OGN"},
		"originally-funny-guys":                  {"OFG"},
		"our-nefarious-endeavor":                 {"ONE"},
		"out-rage-pirates":                       {"ORP"},
		"outcast":                                {"OUT"},
		"outlaws":                                {"OTL", "OUT"},
		"overkill":                               {"OVL"},
		"p2psaurus":                              {"PS"},
		"pirates-against-purchasing-software":    {"PAPS"},
		"partners-in-crime":                      {"PiC"},
		"paradigm":                               {"PDM", "Zeus", "PDMISO", "Paradigm ISO"},
		"paradox":                                {"PDX"},
		"pc_cracking-service":                    {"PC-CS", "PCCS"},
		"pe*trsi*tdt":                            {"Public Enemy + Tristar + Red Sector + The Dream Team"},
		"pentagram":                              {"PTG"},
		"pentium-force-team":                     {"PFT"},
		"persian-genius-team":                    {"PGteam"},
		"phoenix":                                {"PHX"},
		"phreakerz-against-commerce":             {"PAC"},
		"pirates-club-inc":                       {"PC INC"},
		"phrozen-crew":                           {"PC"},
		"pirates-cove":                           {"PC"},
		"pirates-analyze-warez":                  {"PAW"},
		"pirates-gone-crazy":                     {"PGC"},
		"pirates-in-legion":                      {"PiL"},
		"pirates-sick-of-initials":               {"PSi"},
		"pirates-with-attitudes":                 {"PWA"},
		"pirates-releasing-in-mass-extremes":     {"PRiME"},
		"pizza-dox":                              {"PizzaDOX"},
		"plate-steel-productions":                {"PSP"},
		"police":                                 {"PLC"},
		"power-crisis-international":             {"PCI"},
		"portable-apps-crew-europe":              {"PACE"},
		"psycho-corporate-productions":           {"PCP"},
		"predator-666":                           {"PRD666"},
		"primal":                                 {"PML"},
		"prophecy":                               {"PCY"},
		"propaganda":                             {"PROP"},
		"prozac":                                 {"PRO"},
		"ptl-club":                               {"PTL"},
		"postmortem":                             {"PM"},
		"prestige":                               {"PSG", "PST"},
		"protection-fucking-sucks":               {"PFS"},
		"psycho-squad":                           {"PSD"},
		"public-brand-software":                  {"PBS"},
		"public-enemy":                           {"PE"},
		"pyradical":                              {"PYR"},
		"quartex":                                {"QTX", "Quartex PC"},
		quick:                                    {"QUICK"},
		"radical-elite-movement":                 {"REM"},
		"really-awful-music":                     {"RAM"},
		"rage":                                   {"Rage'94"},
		"razordox":                               {rzr, razor, "Razor DOX", "Razor 1911 Documentation Division"},
		"razor-1911":                             {rzr, razor, "Razor CD", "Razor CD Division"},
		"razor-1911-demo":                        {rzr, razor},
		"real-life-then-scene":                   {"RLTS"},
		"real-crazy-artists":                     {"RCA"},
		"real-cocoheads":                         {"RC"},
		"reality-check-network":                  {"RCN"},
		"real-time-pirates":                      {"RTP"},
		"rebels":                                 {"RBS"},
		"r2":                                     {"R2", "RTWO"},
		"recoil":                                 {"RCL"},
		"red-sector-inc":                         {"RSI"},
		"red-green-blue":                         {"RGB"},
		"release-on-rampage":                     {"RoR"},
		"relic":                                  {"REL"},
		"reloaded":                               {"RLD"},
		"relativity":                             {"REV"},
		"reflux":                                 {"RLX"},
		"relentless-pursuit-of-magnificence":     {"RPM", "Relentlessly Pursuing Magnificence"},
		"republic-banana":                        {"RB"},
		"request-to-send":                        {"RTS"},
		"renaissance":                            {"RNS", "RSS"},
		"reign-of-terror":                        {"RoT"},
		"resistance-is-futile":                   {"RiF"},
		"rescue-raider":                          {"RR", "RR INC", "TDI"},
		"resurrection":                           {"RSR", "RES"},
		"revelation":                             {"RVL"},
		"review-of-aquired-warez":                {"RAW"}, //nolint:misspell
		"revenge-crew":                           {"REV"},
		"revolution-project":                     {"RP"},
		"reverse-2-revolutionize":                {"R2R"},
		"reverse-engineers-dream":                {"RED"},
		"reverse-engineering-in-software":        {"REiS"},
		"reverse-engineering-passion-team":       {"REPT"},
		"reviving-intelligent-fast-trading":      {"RiFT"},
		"revolution":                             {"RVL", "RTN"},
		rampage:                                  {"RAMPAGE"},
		"rise-in-superior-couriering":            {"RiSC"},
		"risciso":                                {"RiSC"},
		"rom-1911":                               {"Razor 1911 CD-ROM Division"},
		"romkids":                                {"RMK"},
		"russian-trading-alliance":               {"RTA"},
		"sanxion":                                {"SXN"},
		"saints-and-sinners-group":               {"SSG"},
		"seek-n-destroy":                         {"SND"},
		"scene-charts":                           {"SC"},
		"skid-row":                               {"SR", "Skidrow"},
		"scoopex":                                {"SCX", "SPX"},
		"scooby-snack-magazine":                  {"SSM"},
		"scandal":                                {"SCL"},
		scud:                                     {"SCUD"},
		"scenenotice":                            {"SCN"},
		"scienide":                               {"SCi"},
		"sea-shell-commando":                     {"SSC"},
		"serials-2000":                           {"S2K"},
		"software-exchange":                      {"SEX", "SOFT-EX"},
		"silicon-dream-artists":                  {"SDA"},
		"shallow-grounds":                        {"SG"},
		"share-and-enjoy":                        {"SAE"},
		"shore-cracking-ansi-runners":            {"SCaR"},
		"shmeitcorp":                             {"Shmeit Corp", "SC"},
		"shitonlygerman":                         {"SOG", "Scheisse Deutsch Only"},
		"skillion":                               {"SKN"},
		"shiver":                                 {"SHV"},
		"siege":                                  {"SG"},
		"silent-cracking-force":                  {"SCF"},
		"silent-cracking-service":                {"SCS"},
		"sinister":                               {"SiN"},
		"slaves-of-pain":                         {"SoP"},
		"smokers-in-krime":                       {"SiK"},
		"smegma":                                 {"SMG"},
		"society-of-sharing":                     {"SOS"},
		"society-of-suckers":                     {"SOS"},
		"sodom":                                  {"SDM"},
		"solitudes":                              {"SLT"},
		"some-lonesome-ansi-makers":              {"SLAM"},
		"sorcerers":                              {"SOR"},
		"software-liberation-army":               {"SLA"},
		"software-pirating-coalition":            {"SPC"},
		"software-chronicles-digest":             {"SCD"},
		"software-in-danger":                     {"SID"},
		"software-pirates-inc":                   {"SPI", "Software Pirates"},
		"south-eastern-elite":                    {"SEE"},
		"spetznas":                               {"spetznaz"},
		"spazm":                                  {"SPZ", "SPZM", "Spazm/VGA"},
		"spazm-couriers":                         {"SPZ", "SPZM", "SPAZM"},
		"spectrum":                               {"SPEC"},
		"standards-of-piracy-association":        {"SPA"},
		"static":                                 {"STC"},
		"superior-art-creations":                 {"SAC"},
		"surprise-productions":                   {"SP"},
		"suicide-is-painless":                    {"SiP"},
		"synapse":                                {"SYN"},
		"syndicate-of-dreams":                    {"SOD"},
		"sysop-support-network":                  {"SSN"},
		"sma-posse":                              {"$MA"},
		"syndicate":                              {"SYN"},
		"the-syndicate":                          {"$ynd", "The $yndicate", "The $yndacite"},
		"talent-entertainment":                   {"TLN"},
		"tdu_jam":                                {"TDU-Jam!", "TDU", "TDUJAM", "TDU JAM"},
		"starlight":                              {"SLT"},
		"scum":                                   {"S.C.U.M"},
		"crazy-nation":                           {"CZN"},
		"global-piracy-foundation":               {"GPF"},
		"orbital-one-three":                      {"O13"},
		"secret-warez-people":                    {"SWP"},
		"quantum":                                {"QTM"},
		"repulsion":                              {"RSP"},
		"soncrap":                                {"SC"},
		"axis":                                   {"AX"},
		"bomb-squad":                             {"BS"},
		"cryp70nym":                              {"CrY"},
		"13-omens":                               {"13o"},
		"national-pirate-list":                   {"Bounty"},
		"crime":                                  {"CR", "CRM"},
		"countdown":                              {"CNT", "Count Down"},
		"skeleton-army":                          {"SKL", "The Skeleton Army"},
		"winterhawk-dupe-list":                   {"Wintr", "Big Bird", "BigBird", "BB"},
		"dragon":                                 {"DGN"},
		"team-edge":                              {"EDGE"},
		"team-technotrogens":                     {"TT3", "Team T3"},
		"technobrains":                           {"TCB"},
		"terratron":                              {"TERR"},
		"terror-zone-underground":                {"TZU"},
		"tekno-rage-ampersand-pirasoft":          {"TRPS"},
		"the-amatuer-crackist-tutorial":          {"ACT"}, //nolint:misspell
		"the-artists-guild":                      {"TAG"},
		"the-black-star":                         {"TBS"},
		"the-bitter-end":                         {"TBE"},
		"the-brain-slayer":                       {"TBS"},
		"the-buyers-group":                       {"TBG"},
		"the-brotherhood-of-gods-and-retards":    {"BGR"},
		"the-care-company":                       {tcc},
		"the-canadian-crackers":                  {tcc},
		"the-chronic-krackers":                   {"TCK"},
		"the-cracking-answer":                    {tca},
		"the-crazed-asylum":                      {tca},
		"the-cracking-clan":                      {tcc},
		"the-cradle-traders":                     {"TCT"},
		"the-codeblasters":                       {"TCB"},
		"the-console-division":                   {"TCD"},
		"the-corporation":                        {"CORP"},
		"the-council":                            {cnc},
		"the-courier-association":                {tca},
		"the-cutting-edge":                       {"TCE"},
		"the-cracking-lords":                     {"TCL"},
		"the-damned-souls":                       {"TDS"},
		"the-dark-sector-courier-association":    {"TDSCA"},
		"the-defective-detectives":               {"TDD"},
		"the-dirty-dozen":                        {"TDD"},
		"the-dream-team":                         {"TDT"},
		"the-documentation-network":              {"TDN"},
		"the-dominators":                         {"DOM", "Dominators"},
		"the-elementals-piratelist":              {"TEP"},
		"the-elite-scripting-team":               {"TEST"},
		"the-entertainment-team":                 {"TET"},
		"the-elite-crew":                         {"TEC"},
		"the-faction":                            {"FACTION"},
		"the-firm":                               {"FiRM", "FRM"},
		"the-force-team":                         {"TFT"},
		"the-federation-of-software-theft":       {"FOST"},
		"the-fuck-you-crew":                      {"TFUC"},
		"the-gameboy-charts":                     {"GCharts"},
		"the-gamers-edge":                        {"TGE"},
		"the-game-review":                        {"TGR"},
		"the-game-scene-chart":                   {"TGSC"},
		"the-guild-of-thieves":                   {"TGT"},
		"the-grand-council":                      {"TGC", "Grand Council"},
		"the-hardened-criminals":                 {"THC"},
		"the-hard-hackers":                       {"THH"},
		"the-hammer":                             {"MIR"},
		"the-hard-wares":                         {"THW"},
		"the-hill-people":                        {"THP"},
		"the-humble-guys":                        {"THG", "Humble"},
		"the-kiwi-killers":                       {"TKK"},
		"the-illinois-pirates":                   {"TIP"},
		"the-internet-dream-team":                {"TiDT"},
		"the-lamerz-group":                       {"TLG"},
		"the-inner-circle":                       {"TIC"},
		"the-lightning-crew":                     {"TLC"},
		"the-mappers-guild":                      {"TMG"},
		"the-missing-link":                       {"TML"},
		"the-millennium-group":                   {"TMG"},
		"the-mental-midgets":                     {"TMM"},
		"the-nameless-ones":                      {"TNO"},
		"the-naked-truth-magazine":               {"NTM"},
		"the-new-order-of-sacro_elite":           {"NOOSE"},
		"the-net-monkey-weekly-report": {
			"NWR", "NetMonkey Report", "Netmonkey Weekly Report", "Netmonkey Courier Report",
			"Netmonkey Weekend Report",
		},
		"the-north-west-connection":              {"TNWC"},
		"the-nova-team":                          {"TNT"},
		"the-one-and-only":                       {"TOAO"},
		"the-outlaws":                            {"TOL", "OL"},
		"the-other-side":                         {"TOS"},
		"the-pirate-syndicate":                   {"TPS"},
		"the-pirates-manifesto":                  {"Manifest"},
		"the-pirate-world":                       {"TPW"},
		"the-players-club":                       {tpc},
		"the-phoney-coders":                      {tpc},
		"the-phoney-coders-trainers-division":    {tpc},
		"the-people-upstairs":                    {"TPU"},
		"the-programmers-crew":                   {tpc},
		"the-rapeware-syndicate":                 {"TRWS"},
		"the-reversers-ultimate-epidemic":        {"tRUE"},
		"the-reviewers-guild":                    {"TRG"},
		"the-red-scorpion":                       {trs},
		"the-reservoir-warez-report":             {"Report"},
		"the-sabotage-rebellion-hackers":         {"TSRh"},
		"the-safety-zone":                        {"TSZ"},
		"the-shining-darkness":                   {"TSD"},
		"the-space-pigs":                         {"SP"},
		"the-stealth-pirate-network":             {"TSPN"},
		"the-silents":                            {"TSL"},
		"the-silent-terror":                      {"TST"},
		"the-software-review":                    {"TSR"},
		"the-software-innovation-network":        {"SIN"},
		"the-sinister-syndicate":                 {"TSS"},
		"the-sure-logic-syndicate":               {"SLS"},
		"the-sysops-association-network":         {"TSAN"},
		"the-syndicate-of-original-gangsters":    {"TSOG", "OG SYND"},
		"the-unbiased-dox-report":                {"DR"},
		"the-underground-council":                {"UGC"},
		"the-underworld-corporation":             {"TUC"},
		"the-untouchables":                       {unt},
		"the-warez-alliance":                     {"TWA"},
		"trc-ware-report":                        {"The Ware Report!", "Ware Report"},
		"the-warez-collectors":                   {"TWC"},
		"the-warez-magazine":                     {"The W.A.R.E.Z. Magazine"},
		"the-week-in-warez":                      {"WWN"},
		"the-wondertwins":                        {"TWT"},
		"might-and-magic-bbs":                    {"M&M BBS"},
		"burning-church-bbs":                     {"The Burnin Church BBS", "The Burn'n Church BBS"},
		"realm-of-destruction-bbs":               {"The Realm of Destruction BBS", "TROD BBS"},
		"silent-tower-bbs":                       {"The Silent Tower BBS"},
		"great-white-north-bbs":                  {"TGWN BBS", "The Great White North BBS"},
		"deep-space-9-bbs":                       {"Deep Space Nine BBS", "DS9 BBS"},
		"dead-zone-bbs":                          {"The Dead Zone BBS", "TDZ BBS"},
		"thg-fx":                                 {"The Humble Guys FX", "THG F/X"},
		"tkc*crackers-in-action":                 {"tKC", "CiA"},
		"toads":                                  {"T.O.A.D.S."},
		"toxic":                                  {"TOX"},
		"terrorist-training-camp-bbs":            {"TCC BBS"},
		"ecstatic-sound-production":              {"ESP"},
		"two-minute-warning-bbs":                 {"The Two Minute Warning BBS"},
		"armageddon-support-bbs":                 {"TASB", "The Armageddon Support BBS", "The ASB"},
		"power-grid-bbs":                         {"The Powergrid BBS", "Powergrid BBS", "PG BBS"},
		"trading-and-trading-international-crew": {"TATiC"},
		"tired-of-protection":                    {"TOP"},
		"triad":                                  {"TRI"},
		"trinity-of-triad":                       {"ToT"},
		"trinity-labs-incorporated":              {"TLI"},
		"tristar":                                {trs},
		"tristar-ampersand-red-sector-inc":       {"TRSi", trs, "Tristar"},
		tlf:                                      {"TLF", "TRSi/Lightforce/Fusion"},
		"twilight":                               {"TW"},
		"twilight-zone":                          {"TZ"},
		"twilight-designs-crew":                  {"TDC"},
		"twin-sectors-inc":                       {"TSI"},
		"tyranny":                                {"TYR", "TRN"},
		"twenty-one-twelve-bbs":                  {"2112", "²''²"},
		tsep:                                     {"TSEP"},
		"turbo-nutter-kiwi-bastards":             {"TNKB", "KiWi"},
		"ultra-tech":                             {"UT"},
		"ultra-tech*electro-magnetic-crackers":   {"UT-EMC"},
		"unified-legendary-traders-rising-again": {"ULTRA"},
		"ultra-force":                            {"UF", "Ultraforce"},
		"utilities-in-demand":                    {"UiD"},
		"under-seh-team":                         {"UST"},
		"underground-empire":                     {"UE"},
		"union":                                  {"UNi"},
		"united-albanian-reverse-engineers":      {"UARE"},
		"united-artist-association":              {"UAA"},
		"united-couriers":                        {"UC"},
		"united-cracking-force":                  {"UCF"},
		"universal-crackers-of-the-underground":  {"UCU"},
		"united-group-international":             {"UGI"},
		"united-reverse-engineering-team":        {"URET"},
		"united-software-association*fairlight":  {"USA/Fairlight", "USA/FLT", "USA"},
		"united-states-courier-report":           {"USCR"},
		"united-traders-of-germany":              {"UTG"},
		"united-file-traders":                    {"UFT"},
		"underpl":                                {"UPL"},
		"underground-kidz":                       {"UK"},
		"underground-pirating-syndicate":         {"UPS"},
		"unleashed":                              {"UNL"},
		"underground-cracking-syndicate":         {"UCS"},
		"unpacking-gods":                         {"UG"},
		"untouchables":                           {unt},
		"untouchable-art":                        {unt},
		"velocity-couriers":                      {"VEL"},
		"vendetta":                               {"VND"},
		"vengeance":                              {"VGN", "VEN", "Vengeance"},
		"vengeance-couriers":                     {"VGN"},
		"vertex":                                 {"VTX"},
		"very-strange-warez":                     {"VSW"},
		"victoria-independent-piracy":            {"VIP"},
		"vital-dox":                              {"VD"},
		"vision-factory":                         {"VF"},
		"visions-of-reality":                     {"VOR"},
		"virility":                               {"VRL"},
		"vitality":                               {"VIT", "VTL"},
		"vortex":                                 {"VXT"},
		"vortex-software":                        {"Vortex"},
		"warez-anarchy-review":                   {"WAR"},
		"worldwide-applications-release-system":  {"WARES"},
		"world-domination-force":                 {"WDF"},
		"wave":                                   {"The Wave", cnc},
		"western-area-pirates":                   {"WARP"},
		"delusions-of-grandeur":                  {"DoG"},
		"warrior":                                {"WAR", "WARez RIng ORganization"},
		"wdyl-wtn":                               {"WDYL"},
		"west-coast-cracking-production":         {"WCCP"},
		"well-release-anything":                  {"WRA"},
		"wierd-new-world":                        {"WNW"}, //nolint:misspell
		"wild-cards":                             {"WC", "WC!"},
		"wicked":                                 {"WKD"},
		"wizard-couriers":                        {"WC"},
		"world-wide-couriers":                    {"WWC"},
		"xap":                                    {"EX Apple Pirates"},
		"x_large":                                {"XL"},
		"x_factor":                               {"XFactor"},
		"x_force":                                {"XF", "XForce", "X·Force"},
		"xtreeme":                                {"XT"},
		"youngsters-against-mcafee":              {"YAM"},
		"ypogeios":                               {"YGS"},
		"zero-waiting-time":                      {"ZWT"},
		"zenith":                                 {"ZNTH"},
		"zick-zack-cooperation":                  {"ZZC"},
		"zone":                                   {"z0ne"},
		"silent-chaos":                           {"SC"},
		"complex-ftp":                            {"The Complex"},
		"premiere":                               {"prm"},
		"vdr-lake-ftp":                           {"VDR Lake", "Virtual Dimension Research", "VDR", "VDRLAKE"},
		"z-land-ftp":                             {"Zland"},
		"utwente-ftp":                            {"UT"},
		"sanctuary-ftp":                          {"The Sanctuary", "TS"},
		"rising-sun-ftp":                         {"The Rising Sun"},
		"oriental-pearl-ftp":                     {"The Oriental Pearl", "TOP"},
		"desert-inn-ftp":                         {"The Desert Inn"},
		"carpenters-haven-ftp":                   {"The Carpenter's Haven"},
		"citadel-ftp":                            {"The Citadel"},
		"the-copyright-power":                    {"TCP"},
		"tekno-rage":                             {"TR"},
		"pirasoft":                               {"PS"},
		"novastorm":                              {"NS"},
		"kovert-spreaders-inc":                   {"KSI"},
		"virtual-dimension-research":             {"VDR"},
		"digital-pirating-alliance":              {"DPA"},
		"central-crime-association":              {"CCA"},
		"dextrose":                               {"DX"},
		"executive":                              {"EXCC", "EXE"},
		"follow-my-religion":                     {"FMR"},
		"grind-and-mcarec":                       {"GAM"},
		"immortals":                              {"IMM", "IMS"},
		"jazz-united-couriers":                   {"JUC"},
		"karma":                                  {"KRMA", "KRM"},
		"league":                                 {"LGE"},
		"master-piece":                           {"MP"},
		"men-in-black":                           {"MIB"},
		"the-seekers-oasis":                      {"TSO"},
		"we-love-warez":                          {"WLW"},
		"warez-in-progress":                      {"WIP"},
		"thunder":                                {"THD"},
		"black-lotus-couriers":                   {"BLC"},
		"chrome-matrix":                          {"CM"},
		"co_operative":                           {"Co-Op"},
		"children-of-the-grave":                  {"Cotg"},
		"house-experience":                       {"HX"},
		"phoenix-hitmen":                         {"PHX"},
		"18plus2":                                {"18+2"},
		"abrupt":                                 {"ABT"},
		"arcane":                                 {"ARC"},
		"damage-inkorporated-enterprises-2084":   {"DIE"},
		"central-division":                       {"CD"},
		"conehead-smos-games":                    {"SMOS", "SMS"},
		"superficial":                            {"SfC"},
		"real-warez-traders":                     {"RWT"},
		"the-new-breed":                          {"TNB"},
		"the-force-traderz":                      {"TFT"},
		"the-gathering":                          {"TGA"},
		"the-couriers-digest":                    {"TCD"},
		"diebels-drinking-team":                  {"DDT"},
		"pinnacle":                               {"PNC"},
		"providence":                             {"PIE"},
		"professionally-cracked-warez":           {"PCW"},
		"vigor":                                  {"VG"},
		"violence":                               {"VIO"},
		"menace-to-society":                      {"MTS"},
		"miracle":                                {"MRC"},
		"legion":                                 {"LGN"},
		"0day_dump":                              {"0DD"},
		"doom":                                   {"Doom64", "DM"},
		"lightning-couriers":                     {"LGT"},
		"critical":                               {"CRT"},
		"cats-are-cool":                          {"CRC"},
		"forces-of-darkness":                     {"FOD"},
		"death-and-destruction":                  {"DAD"},
		"demolition":                             {"DMN"},
		"densetsu":                               {dst},
		"inner-sanctum-bbs":                      {"TIS", "The Inner Sanctum"},
		"onyx":                                   {"ox"},
		"federation-against-class":               {"FAC"},
		"sneakers":                               {"SNK", "SKS"},
		"sneakers-ftp":                           {"SnK"},
		"highway-to-hell-ftp":                    {"H2H", "Highway II Hell", "highway 2 hell"},
		"pleasure-n-joy":                         {"Pleasure'n'joy", "PNJ"},
		"iarqua-57":                              {"IRQ", "IRQ57", "IRQ 57"},
		"shit-hot-trading-posse":                 {"SHTP"},
		"sonic-mind-warp":                        {"SMW"},
		"mentality":                              {"mnt"},
		"brand-beer-ii-ftp":                      {"bb2"},
		"the-orgasmik-krew":                      {"TOK"},
		"pirates-cove-ftp":                       {"PC"},
		"toxic-dump-ftp":                         {"TTD"},
		"darkstar":                               {"DS", "Dark*Star"},
		"orbit":                                  {"OBT"},
		"distortion":                             {dst, "DIS"},
		"house-of-music-ftp":                     {"HOM"},
		"phantom-quanqiutong-ftp":                {"QQT", "THP-QQT"},
		"the-crackerz-company":                   {tcc},
		"armageddon":                             {"AMG"},
		"creator-of-darkness":                    {"COD"},
		"dark-forces":                            {"DF"},
		"outbreak-couriers":                      {"OB"},
		"dead-legends-society":                   {"DLS"},
		"parasite":                               {"PST"},
		"emerald":                                {"ERD"},
		"flatline":                               {"FL"},
		"independent-releasing":                  {"iR"},
		"mantis":                                 {"MNT"},
		"australian-elite-force":                 {"AEF"},
		"core-dump":                              {"CD"},
		"world-wide-releasing":                   {"WWR"},
		"far-beyond-insanity":                    {"Fbi"},
		"the-reservoir-dogs":                     {"TRD"},
		"new-order-bbs":                          {"The New Order", "tno"},
		"romlight":                               {"RLT"},
		"lifeless":                               {"LL"},
		"original-gun-clappers":                  {"OGC"},
		"bribe":                                  {"BBE"},
		"black-circle-bbs":                       {"TBC"},
		"lords-of-deception":                     {"l0D, lOD"},
		"last-resort-ftp":                        {"TLR", "The Last Resort"},
		"orgasm":                                 {"OGM"},
		"the-age-of-creation":                    {"tac"},
		"new-vision-couriers":                    {"NVC"},
		"celebre":                                {"CLB"},
		"ez-way-ftp":                             {"The Ez Way", "EZ", "eZWAY"},
		"divide-by-zero-ftp":                     {"dbz"},
		"coke-ftp":                               {"cOCA cOLA"},
		"atlantis-ftp":                           {"atl"},
		"air-force-one-ftp":                      {"af1", "AirForce One"},
		"allied-mind-force":                      {"AMF"},
		"bad-conscience-inc":                     {"BCi"},
		"sphere-of-speed-bbs":                    {"sos"},
		"sphere-of-speed-ftp":                    {"sos"},
		"x_pression-design":                      {"X Pression", "xpression"},
		"the-flame-arrows":                       {"TFA", "TFAiSO", "TFaMP", "TFAServices", "TFAAmiga"},
		"ice-cold-productions":                   {"ICP", "I<P"},
		"next-generation-pirates":                {"NGP"},
		"digital-neurosis":                       {"DN"},
		"rabid-neurosis":                         {"RNS"},
		"rok":                                    {"Magic Island ROK", "Island ROK"},
		"rise":                                   {"REALLY iNTO SPREADiNG ELiTE", "RISEiSO"},
		"nuclear-dust-ftp":                       {"nud"},
		"pre-whore-house-ftp":                    {"pwh"},
		"pir8tes-pavilion-ftp":                   {"Pirates Pavilion", "pir"},
		"fire-site-ftp":                          {"FireSite"},
		"cemetery-gates-ftp":                     {"cm-g", "cmg"},
		"rezurection":                            {"Rez"},
		"magnetic-fields-ftp":                    {"MF", "MFiSO"},
		"psychowarez":                            {"pwz"},
		"judgement":                              {"JDt"},
		"menace-ii-bbs":                          {"Menace 2", "Menace ]["},
		"eiserne-front-bbs":                      {"EF"},
		"x_factor-bbs":                           {"X Factor", "XFactor"},
		"edge-of-honor-whq-bbs":                  {"Edge of Honor", "EOH"},
		"akira-group-93":                         {"Akira 93", "AKA"},
		"fighting-force":                         {"ffo"},
		"stormzone-ftp":                          {"StormZone", "Storm Zone", "SZ"},
		"the-digital-afterlife":                  {"TDA"},
		"shock-demo":                             {"Shock!"},
		"nectar-base-bbs":                        {"The Nectar Base BBS"},
		"sonic":                                  {"Sonic64", "son"},
		"mnemonic-crackers":                      {"mnc"},
		"shock":                                  {"SHOCKiSO", "SHOCK iSO", "SHOCKpDA"},
		"crime-syndicate-bbs":                    {"TCS BBS", "The Crime Syndicate BBS"},
		"palace-of-exile-bbs":                    {"The Palace of Exile BBS"},
		"cartel-bbs":                             {"The Cartel BBS"},
		"crime-cartel-bbs":                       {"TCC BBS", "The Crime Cartel BBS"},
		"fx-bbs":                                 {"F/X BBS"},
		"latitude-zero-bbs":                      {"LZ BBS"},
		"countdown-to-extinction-bbs":            {"CTE BBS"},
		"vision_x-bbs":                           {"Vision X BBS Software"},
		"hardwired-bbs":                          {"Hard Wired BBS"},
		"jungle-bbs":                             {"The Jungle BBS"},
		"lush-software-designs-bbs":              {"LSD BBS"},
		"revolutions-per-minute-bbs":             {"RPM BBS"},
		"dark-crusade-bbs":                       {"The Dark Crusade BBS", "TDC BBS"},
		"beyond-the-realm-of-reality-bbs":        {"Beyond BBS", "BRR BBS"},
		"psycho_neurosis-bbs":                    {"Psychoneurosis BBS", "Psycho Neurosis BBS"},
	}
	return &list
}

// Initialism returns the alternative spellings, acronyms and initialisms for the URL path.
// Or an empty slice if the URL path has no initialism.
//
// Example:
//
//	Initialism("the-firm") = []string{"FiRM, FRM"}
//	Initialism("defacto2") = []string{"DF2"}
func Initialism(path Path) []string {
	initialism := *Initialisms()
	return initialism[path]
}

// IsInitialism returns true if the URL path has an initialism.
//
// Example:
//
//	IsInitialism("the-firm") = true
//	IsInitialism("defacto2") = true
//	IsInitialism("some-random-bbs") = false
func IsInitialism(path Path) bool {
	initialism := *Initialisms()
	_, match := initialism[path]
	return match
}

// Join returns the alternative spellings, acronyms and initialisms for the
// URL path as a comma separated string.
// Or an empty string if the URL path has no initialism.
//
// Example:
//
//	Join("the-firm") = "FiRM, FRM"
//	Join("defacto2") = "DF2"
func Join(path Path) string {
	i := Initialism(path)
	if len(i) == 0 {
		return ""
	}
	return strings.Join(i, ", ")
}

// Match returns the list of initialisms that match the given string.
func Match(s string) []Path {
	var partials []Path
	for partial, values := range maps.All(*Initialisms()) {
		for value := range slices.Values(values) {
			if strings.EqualFold(value, s) {
				partials = append(partials, partial)
			}
		}
	}
	return partials
}
